# DATA CLEANING

## CENTRAL LONDON DATA SET

In [1]:
# Import all the necessary packages.
import pandas as pd
import numpy as np
from datetime import datetime

# Optional - Ignore warnings.
import warnings
warnings.filterwarnings('ignore')
  
# Read the provided CSV file/data set.            
london_central = pd.read_csv('Central London.csv') 

# View DataFrame.
london_central.head()

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
0        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
1        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
2        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
3        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
4        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   

                             Location    Survey date Weather         Time  \
0  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0600 - 0615   
1  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0615 - 0630   
2  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0630 - 0645   
3  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0645 - 0700   
4  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0700 - 0715   

                        Period   Direction  Start hour  Start minute  \
0  Early Morning (06:00-07:00)  Northbound         6.0           0.0   
1  Early Morning (06:00-07:00)  Northbound         6.0          15.0   
2  Early Morning (06:00-07:00)  Northbound         6.0          30.0   
3  Early Morning (06:00-07:00)  Northbound         6.0          45.0   
4        AM peak (07:00-10:00)  Northbound         7.0           0.0   

   Number of private cycles  Number of cycle hire bikes  Total cycles  \
0                       0.0                         0.0           0.0   
1                      15.0                         0.0          15.0   
2                      35.0                         0.0          35.0   
3                      59.0                         2.0          61.0   
4                      73.0                         0.0          73.0   

   Unnamed: 14  Unnamed: 15  Unnamed: 16  
0          NaN          NaN          NaN  
1          NaN          NaN          NaN  
2          NaN          NaN          NaN  
3          NaN          NaN          NaN  
4          NaN          NaN          NaN

In [2]:
# Any missing values?
london_central.isnull().sum()          

Survey wave (calendar quarter)     290203
Equivalent financial quarter       290203
Site ID                            290203
Location                           290203
Survey date                        300359
Weather                            302037
Time                               290203
Period                             290203
Direction                          290203
Start hour                         290203
Start minute                       290203
Number of private cycles           290267
Number of cycle hire bikes         290267
Total cycles                       290203
Unnamed: 14                       1048366
Unnamed: 15                       1048366
Unnamed: 16                       1048366
dtype: int64

In [3]:
# Explore the data.
london_central.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048366 entries, 0 to 1048365
Data columns (total 17 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   Survey wave (calendar quarter)  758163 non-null  object 
 1   Equivalent financial quarter    758163 non-null  object 
 2   Site ID                         758163 non-null  object 
 3   Location                        758163 non-null  object 
 4   Survey date                     748007 non-null  object 
 5   Weather                         746329 non-null  object 
 6   Time                            758163 non-null  object 
 7   Period                          758163 non-null  object 
 8   Direction                       758163 non-null  object 
 9   Start hour                      758163 non-null  float64
 10  Start minute                    758163 non-null  float64
 11  Number of private cycles        758099 non-null  float64
 12  Number of cycl

In [4]:
# Drop last three columns as contain no values.
L_centr_fnl = london_central.drop(columns=['Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16']).reset_index(drop=True)

# View DataFrame.
print(L_centr_fnl.shape)
L_centr_fnl.head()

(1048366, 14)


Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
0        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
1        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
2        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
3        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
4        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   

                             Location    Survey date Weather         Time  \
0  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0600 - 0615   
1  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0615 - 0630   
2  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0630 - 0645   
3  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0645 - 0700   
4  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0700 - 0715   

                        Period   Direction  Start hour  Start minute  \
0  Early Morning (06:00-07:00)  Northbound         6.0           0.0   
1  Early Morning (06:00-07:00)  Northbound         6.0          15.0   
2  Early Morning (06:00-07:00)  Northbound         6.0          30.0   
3  Early Morning (06:00-07:00)  Northbound         6.0          45.0   
4        AM peak (07:00-10:00)  Northbound         7.0           0.0   

   Number of private cycles  Number of cycle hire bikes  Total cycles  
0                       0.0                         0.0           0.0  
1                      15.0                         0.0          15.0  
2                      35.0                         0.0          35.0  
3                      59.0                         2.0          61.0  
4                      73.0                         0.0          73.0

In [5]:
L_centr_fnl.tail()

Survey wave (calendar quarter) Equivalent financial quarter Site ID  \
1048361                            NaN                          NaN     NaN   
1048362                            NaN                          NaN     NaN   
1048363                            NaN                          NaN     NaN   
1048364                            NaN                          NaN     NaN   
1048365                            NaN                          NaN     NaN   

        Location Survey date Weather Time Period Direction  Start hour  \
1048361      NaN         NaN     NaN  NaN    NaN       NaN         NaN   
1048362      NaN         NaN     NaN  NaN    NaN       NaN         NaN   
1048363      NaN         NaN     NaN  NaN    NaN       NaN         NaN   
1048364      NaN         NaN     NaN  NaN    NaN       NaN         NaN   
1048365      NaN         NaN     NaN  NaN    NaN       NaN         NaN   

         Start minute  Number of private cycles  Number of cycle hire bikes  \
1048361           NaN                       NaN                         NaN   
1048362           NaN                       NaN                         NaN   
1048363           NaN                       NaN                         NaN   
1048364           NaN                       NaN                         NaN   
1048365           NaN                       NaN                         NaN   

         Total cycles  
1048361           NaN  
1048362           NaN  
1048363           NaN  
1048364           NaN  
1048365           NaN

In [6]:
# Drop the rows where all elements are missing.
L_centr_fnl_0 = L_centr_fnl.dropna(how='all')

# View DataFrame.
print(L_centr_fnl_0.shape)
L_centr_fnl_0.head()

(758163, 14)


Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
0        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
1        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
2        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
3        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
4        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   

                             Location    Survey date Weather         Time  \
0  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0600 - 0615   
1  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0615 - 0630   
2  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0630 - 0645   
3  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0645 - 0700   
4  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0700 - 0715   

                        Period   Direction  Start hour  Start minute  \
0  Early Morning (06:00-07:00)  Northbound         6.0           0.0   
1  Early Morning (06:00-07:00)  Northbound         6.0          15.0   
2  Early Morning (06:00-07:00)  Northbound         6.0          30.0   
3  Early Morning (06:00-07:00)  Northbound         6.0          45.0   
4        AM peak (07:00-10:00)  Northbound         7.0           0.0   

   Number of private cycles  Number of cycle hire bikes  Total cycles  
0                       0.0                         0.0           0.0  
1                      15.0                         0.0          15.0  
2                      35.0                         0.0          35.0  
3                      59.0                         2.0          61.0  
4                      73.0                         0.0          73.0

In [7]:
# Check missing values.
L_centr_fnl_0.isnull().sum()

Survey wave (calendar quarter)        0
Equivalent financial quarter          0
Site ID                               0
Location                              0
Survey date                       10156
Weather                           11834
Time                                  0
Period                                0
Direction                             0
Start hour                            0
Start minute                          0
Number of private cycles             64
Number of cycle hire bikes           64
Total cycles                          0
dtype: int64

### Cleaning Date and Time related Columns

In [8]:
# Split 'Survey wave (calendar quarter)' column into three new columns.
L_centr_fnl_0['Survey_wave_year'] = L_centr_fnl_0['Survey wave (calendar quarter)'].str.split(' ', expand = True)[0]
L_centr_fnl_0['Survey_wave_quater'] = L_centr_fnl_0['Survey wave (calendar quarter)'].str.split(' ', expand = True)[1]
L_centr_fnl_0['Survey_wave_months'] = L_centr_fnl_0['Survey wave (calendar quarter)'].str.split(' ', expand = True)[2]

# View DataFrame.
L_centr_fnl_0.head()

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
0        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
1        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
2        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
3        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
4        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   

                             Location    Survey date Weather         Time  \
0  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0600 - 0615   
1  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0615 - 0630   
2  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0630 - 0645   
3  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0645 - 0700   
4  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0700 - 0715   

                        Period   Direction  Start hour  Start minute  \
0  Early Morning (06:00-07:00)  Northbound         6.0           0.0   
1  Early Morning (06:00-07:00)  Northbound         6.0          15.0   
2  Early Morning (06:00-07:00)  Northbound         6.0          30.0   
3  Early Morning (06:00-07:00)  Northbound         6.0          45.0   
4        AM peak (07:00-10:00)  Northbound         7.0           0.0   

   Number of private cycles  Number of cycle hire bikes  Total cycles  \
0                       0.0                         0.0           0.0   
1                      15.0                         0.0          15.0   
2                      35.0                         0.0          35.0   
3                      59.0                         2.0          61.0   
4                      73.0                         0.0          73.0   

  Survey_wave_year Survey_wave_quater Survey_wave_months  
0             2014                 Q1    (January-March)  
1             2014                 Q1    (January-March)  
2             2014                 Q1    (January-March)  
3             2014                 Q1    (January-March)  
4             2014                 Q1    (January-March)

In [9]:
# Remove brackets in 'Survey_wave_months' column.
L_centr_fnl_0['Survey_wave_months'] = L_centr_fnl_0['Survey_wave_months'].str.replace('(','')
L_centr_fnl_0['Survey_wave_months'] = L_centr_fnl_0['Survey_wave_months'].str.replace(')','')

# View DataFrame
L_centr_fnl_0.head()

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
0        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
1        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
2        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
3        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
4        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   

                             Location    Survey date Weather         Time  \
0  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0600 - 0615   
1  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0615 - 0630   
2  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0630 - 0645   
3  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0645 - 0700   
4  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0700 - 0715   

                        Period   Direction  Start hour  Start minute  \
0  Early Morning (06:00-07:00)  Northbound         6.0           0.0   
1  Early Morning (06:00-07:00)  Northbound         6.0          15.0   
2  Early Morning (06:00-07:00)  Northbound         6.0          30.0   
3  Early Morning (06:00-07:00)  Northbound         6.0          45.0   
4        AM peak (07:00-10:00)  Northbound         7.0           0.0   

   Number of private cycles  Number of cycle hire bikes  Total cycles  \
0                       0.0                         0.0           0.0   
1                      15.0                         0.0          15.0   
2                      35.0                         0.0          35.0   
3                      59.0                         2.0          61.0   
4                      73.0                         0.0          73.0   

  Survey_wave_year Survey_wave_quater Survey_wave_months  
0             2014                 Q1      January-March  
1             2014                 Q1      January-March  
2             2014                 Q1      January-March  
3             2014                 Q1      January-March  
4             2014                 Q1      January-March

In [10]:
# Change dtype of 'Survey_wave_year' column to integer.
L_centr_fnl_0['Survey_wave_year'] = L_centr_fnl_0['Survey_wave_year'].astype(int)

In [11]:
# Replace blank values with NaN in 'Survey date' column.
L_centr_fnl_0['Survey date'] = L_centr_fnl_0['Survey date'].replace(r'^\s*$', np.nan, regex=True)

In [12]:
# Split 'Survey date' column into two new columns.
L_centr_fnl_0[['Survey_week_day', 'Survey_date']] = L_centr_fnl_0['Survey date'].\
apply(lambda x: pd.Series(str(x).split(',')))

# View DataFrame.
L_centr_fnl_0.head()

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
0        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
1        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
2        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
3        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
4        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   

                             Location    Survey date Weather         Time  \
0  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0600 - 0615   
1  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0615 - 0630   
2  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0630 - 0645   
3  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0645 - 0700   
4  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0700 - 0715   

                        Period   Direction  Start hour  Start minute  \
0  Early Morning (06:00-07:00)  Northbound         6.0           0.0   
1  Early Morning (06:00-07:00)  Northbound         6.0          15.0   
2  Early Morning (06:00-07:00)  Northbound         6.0          30.0   
3  Early Morning (06:00-07:00)  Northbound         6.0          45.0   
4        AM peak (07:00-10:00)  Northbound         7.0           0.0   

   Number of private cycles  Number of cycle hire bikes  Total cycles  \
0                       0.0                         0.0           0.0   
1                      15.0                         0.0          15.0   
2                      35.0                         0.0          35.0   
3                      59.0                         2.0          61.0   
4                      73.0                         0.0          73.0   

   Survey_wave_year Survey_wave_quater Survey_wave_months Survey_week_day  \
0              2014                 Q1      January-March             ven   
1              2014                 Q1      January-March             ven   
2              2014                 Q1      January-March             ven   
3              2014                 Q1      January-March             ven   
4              2014                 Q1      January-March             ven   

  Survey_date  
0    24/01/14  
1    24/01/14  
2    24/01/14  
3    24/01/14  
4    24/01/14

In [13]:
# Drop 'Survey_week_day' column.
L_centr_fnl_0 = L_centr_fnl_0.drop(columns='Survey_week_day').reset_index(drop=True)

In [14]:
# Remove whitespaces in 'Survey_date' column.
L_centr_fnl_0['Survey_date'] = L_centr_fnl_0['Survey_date'].str.replace(' ', '')

In [15]:
# Convert 'Survey_date' column to datetime dtype.
L_centr_fnl_0['Survey_date_dt'] = pd.to_datetime(L_centr_fnl_0['Survey_date'], format = '%d/%m/%y')

# View DataFrame.
L_centr_fnl_0.head()

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
0        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
1        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
2        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
3        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
4        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   

                             Location    Survey date Weather         Time  \
0  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0600 - 0615   
1  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0615 - 0630   
2  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0630 - 0645   
3  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0645 - 0700   
4  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0700 - 0715   

                        Period   Direction  Start hour  Start minute  \
0  Early Morning (06:00-07:00)  Northbound         6.0           0.0   
1  Early Morning (06:00-07:00)  Northbound         6.0          15.0   
2  Early Morning (06:00-07:00)  Northbound         6.0          30.0   
3  Early Morning (06:00-07:00)  Northbound         6.0          45.0   
4        AM peak (07:00-10:00)  Northbound         7.0           0.0   

   Number of private cycles  Number of cycle hire bikes  Total cycles  \
0                       0.0                         0.0           0.0   
1                      15.0                         0.0          15.0   
2                      35.0                         0.0          35.0   
3                      59.0                         2.0          61.0   
4                      73.0                         0.0          73.0   

   Survey_wave_year Survey_wave_quater Survey_wave_months Survey_date  \
0              2014                 Q1      January-March    24/01/14   
1              2014                 Q1      January-March    24/01/14   
2              2014                 Q1      January-March    24/01/14   
3              2014                 Q1      January-March    24/01/14   
4              2014                 Q1      January-March    24/01/14   

  Survey_date_dt  
0     2014-01-24  
1     2014-01-24  
2     2014-01-24  
3     2014-01-24  
4     2014-01-24

In [16]:
# Extract year from Survey_date_dt column.
L_centr_fnl_0['Year'] = L_centr_fnl_0['Survey_date_dt'].dt.strftime('%Y')

# Replace NaN values to 0 and convert values in the column to integer.
L_centr_fnl_0['Year'] = L_centr_fnl_0['Year'].fillna(0)
L_centr_fnl_0['Year'] = L_centr_fnl_0['Year'].astype(int)

# Compare extracted year to Survey_wave_year column.
L_centr_fnl_0[(L_centr_fnl_0['Survey_wave_year'] !=  L_centr_fnl_0['Year']) & (L_centr_fnl_0['Year'] > 0)]

# 648 entries belongs to the wrong year => Survey wave period != calendar period.

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
83192      2014 Q4 (October-December)                   2014-15 Q3  CENCY050   
83193      2014 Q4 (October-December)                   2014-15 Q3  CENCY050   
83194      2014 Q4 (October-December)                   2014-15 Q3  CENCY050   
83195      2014 Q4 (October-December)                   2014-15 Q3  CENCY050   
83196      2014 Q4 (October-December)                   2014-15 Q3  CENCY050   
...                               ...                          ...       ...   
613179     2019 Q4 (October-December)                   2019-20 Q3  CENCY104   
613180     2019 Q4 (October-December)                   2019-20 Q3  CENCY104   
613181     2019 Q4 (October-December)                   2019-20 Q3  CENCY104   
613182     2019 Q4 (October-December)                   2019-20 Q3  CENCY104   
613183     2019 Q4 (October-December)                   2019-20 Q3  CENCY104   

                   Location    Survey date Weather         Time  \
83192   Aldgate High Street  lun, 12/01/15     Wet  2000 - 2015   
83193   Aldgate High Street  lun, 12/01/15     Wet  2015 - 2030   
83194   Aldgate High Street  lun, 12/01/15     Wet  2030 - 2045   
83195   Aldgate High Street  lun, 12/01/15     Wet  2045 - 2100   
83196   Aldgate High Street  lun, 12/01/15     Wet  2100 - 2115   
...                     ...            ...     ...          ...   
613179     Calthorpe Street  lun, 20/01/20     Dry  2045 - 2100   
613180     Calthorpe Street  lun, 20/01/20     Dry  2100 - 2115   
613181     Calthorpe Street  lun, 20/01/20     Dry  2115 - 2130   
613182     Calthorpe Street  lun, 20/01/20     Dry  2130 - 2145   
613183     Calthorpe Street  lun, 20/01/20     Dry  2145 - 2200   

                       Period   Direction  Start hour  Start minute  \
83192   Evening (19:00-22:00)   Eastbound        20.0           0.0   
83193   Evening (19:00-22:00)   Eastbound        20.0          15.0   
83194   Evening (19:00-22:00)   Eastbound        20.0          30.0   
83195   Evening (19:00-22:00)   Eastbound        20.0          45.0   
83196   Evening (19:00-22:00)   Eastbound        21.0           0.0   
...                       ...         ...         ...           ...   
613179  Evening (19:00-22:00)  Southbound        20.0          45.0   
613180  Evening (19:00-22:00)  Southbound        21.0           0.0   
613181  Evening (19:00-22:00)  Southbound        21.0          15.0   
613182  Evening (19:00-22:00)  Southbound        21.0          30.0   
613183  Evening (19:00-22:00)  Southbound        21.0          45.0   

        Number of private cycles  Number of cycle hire bikes  Total cycles  \
83192                        0.0                         0.0           0.0   
83193                        0.0                         0.0           0.0   
83194                        1.0                         0.0           1.0   
83195                        0.0                         0.0           0.0   
83196                        0.0                         0.0           0.0   
...                          ...                         ...           ...   
613179                       0.0                         0.0           0.0   
613180                       1.0                         1.0           2.0   
613181                       0.0                         0.0           0.0   
613182                       0.0                         0.0           0.0   
613183                       3.0                         0.0           3.0   

        Survey_wave_year Survey_wave_quater Survey_wave_months Survey_date  \
83192               2014                 Q4   October-December    12/01/15   
83193               2014                 Q4   October-December    12/01/15   
83194               2014                 Q4   October-December    12/01/15   
83195               2014                 Q4   October-December    12/01/15   
83196               2014                 Q4   October-Decembe

In [17]:
# Replace missing years in the Year column with years from Survey_wave_year column.
L_centr_fnl_0['Year'] = np.where((L_centr_fnl_0['Survey_wave_year'] !=  L_centr_fnl_0['Year']) & 
                                 (L_centr_fnl_0['Year'] == 0), 
                                 L_centr_fnl_0['Survey_wave_year'],
                                 L_centr_fnl_0['Year'])

# Check the output.
L_centr_fnl_0[L_centr_fnl_0['Year'] == 0]

Empty DataFrame
Columns: [Survey wave (calendar quarter), Equivalent financial quarter, Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of private cycles, Number of cycle hire bikes, Total cycles, Survey_wave_year, Survey_wave_quater, Survey_wave_months, Survey_date, Survey_date_dt, Year]
Index: []

In [18]:
# Extract year from Survey_date_dt column.
L_centr_fnl_0['Month'] = L_centr_fnl_0['Survey_date_dt'].dt.strftime('%B')
L_centr_fnl_0.head()

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
0        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
1        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
2        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
3        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
4        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   

                             Location    Survey date Weather         Time  \
0  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0600 - 0615   
1  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0615 - 0630   
2  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0630 - 0645   
3  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0645 - 0700   
4  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0700 - 0715   

                        Period   Direction  Start hour  ...  \
0  Early Morning (06:00-07:00)  Northbound         6.0  ...   
1  Early Morning (06:00-07:00)  Northbound         6.0  ...   
2  Early Morning (06:00-07:00)  Northbound         6.0  ...   
3  Early Morning (06:00-07:00)  Northbound         6.0  ...   
4        AM peak (07:00-10:00)  Northbound         7.0  ...   

   Number of private cycles  Number of cycle hire bikes  Total cycles  \
0                       0.0                         0.0           0.0   
1                      15.0                         0.0          15.0   
2                      35.0                         0.0          35.0   
3                      59.0                         2.0          61.0   
4                      73.0                         0.0          73.0   

   Survey_wave_year  Survey_wave_quater Survey_wave_months Survey_date  \
0              2014                  Q1      January-March    24/01/14   
1              2014                  Q1      January-March    24/01/14   
2              2014                  Q1      January-March    24/01/14   
3              2014                  Q1      January-March    24/01/14   
4              2014                  Q1      January-March    24/01/14   

  Survey_date_dt  Year    Month  
0     2014-01-24  2014  January  
1     2014-01-24  2014  January  
2     2014-01-24  2014  January  
3     2014-01-24  2014  January  
4     2014-01-24  2014  January  

[5 rows x 21 columns]

In [19]:
# Create a new column 'Quarter' and assign months from Month columns to the relevant calendar quarters.
L_centr_fnl_0['Quarter'] = ''

L_centr_fnl_0.loc[(L_centr_fnl_0['Month'] ==  'January') | 
                  (L_centr_fnl_0['Month'] ==  'February') |
                  (L_centr_fnl_0['Month'] ==  'March'), 
                  'Quarter'] = 'Q1'

L_centr_fnl_0.loc[(L_centr_fnl_0['Month'] ==  'April') | 
                  (L_centr_fnl_0['Month'] ==  'May') |
                  (L_centr_fnl_0['Month'] ==  'June'), 
                  'Quarter'] = 'Q2'

L_centr_fnl_0.loc[(L_centr_fnl_0['Month'] ==  'July') | 
                  (L_centr_fnl_0['Month'] ==  'August') |
                  (L_centr_fnl_0['Month'] ==  'September'), 
                  'Quarter'] = 'Q3'

L_centr_fnl_0.loc[(L_centr_fnl_0['Month'] ==  'October') | 
                  (L_centr_fnl_0['Month'] ==  'November') |
                  (L_centr_fnl_0['Month'] ==  'December'), 
                  'Quarter'] = 'Q4'

In [20]:
# Compare assigned quarters to Survey_wave_quater column.
L_centr_fnl_0[(L_centr_fnl_0['Survey_wave_quater'] !=  L_centr_fnl_0['Quarter']) & (L_centr_fnl_0['Quarter'] != '')]

# 25698 entries belongs to the wrong quarter => Survey wave period != calendar period.

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
24832         2014 Q1 (January-March)                   2013-14 Q4  CENCY198   
24833         2014 Q1 (January-March)                   2013-14 Q4  CENCY198   
24834         2014 Q1 (January-March)                   2013-14 Q4  CENCY198   
24835         2014 Q1 (January-March)                   2013-14 Q4  CENCY198   
24836         2014 Q1 (January-March)                   2013-14 Q4  CENCY198   
...                               ...                          ...       ...   
757902    2021 Q4 (October-December)                    2021-22 Q3  CENCY209   
757903    2021 Q4 (October-December)                    2021-22 Q3  CENCY209   
757904    2021 Q4 (October-December)                    2021-22 Q3  CENCY209   
757905    2021 Q4 (October-December)                    2021-22 Q3  CENCY209   
757906    2021 Q4 (October-December)                    2021-22 Q3  CENCY209   

                                  Location    Survey date Weather  \
24832   Riverside Walk (Albert Embankment)  mer, 07/05/14     Dry   
24833   Riverside Walk (Albert Embankment)  mer, 07/05/14     Dry   
24834   Riverside Walk (Albert Embankment)  mer, 07/05/14     Dry   
24835   Riverside Walk (Albert Embankment)  mer, 07/05/14     Dry   
24836   Riverside Walk (Albert Embankment)  mer, 07/05/14     Dry   
...                                    ...            ...     ...   
757902                     Sidmouth Square  mer, 29/09/21     Dry   
757903                     Sidmouth Square  mer, 29/09/21     Dry   
757904                     Sidmouth Square  mer, 29/09/21     Dry   
757905                     Sidmouth Square  mer, 29/09/21     Dry   
757906                     Sidmouth Square  mer, 29/09/21     Dry   

               Time                       Period   Direction  Start hour  ...  \
24832   0600 - 0615  Early Morning (06:00-07:00)  Northbound         6.0  ...   
24833   0615 - 0630  Early Morning (06:00-07:00)  Northbound         6.0  ...   
24834   0630 - 0645  Early Morning (06:00-07:00)  Northbound         6.0  ...   
24835   0645 - 0700  Early Morning (06:00-07:00)  Northbound         6.0  ...   
24836   0700 - 0715        AM peak (07:00-10:00)  Northbound         7.0  ...   
...             ...                          ...         ...         ...  ...   
757902  2045 - 2100        Evening (19:00-22:00)   Westbound        20.0  ...   
757903  2100 - 2115        Evening (19:00-22:00)   Westbound        21.0  ...   
757904  2115 - 2130        Evening (19:00-22:00)   Westbound        21.0  ...   
757905  2130 - 2145        Evening (19:00-22:00)   Westbound        21.0  ...   
757906  2145 - 2200        Evening (19:00-22:00)   Westbound        21.0  ...   

        Number of cycle hire bikes  Total cycles  Survey_wave_year  \
24832                          0.0           0.0              2014   
24833                          0.0           1.0              2014   
24834                          1.0           7.0              2014   
24835                          0.0           2.0              2014   
24836                          0.0           4.0              2014   
...                            ...           ...               ...   
757902                         4.0          13.0              2021   
757903                         0.0          11.0              2021   
757904                         1.0          11.0              2021   
757905                         0.0          13.0              2021   
757906                         2.0          10.0              2021   

        Survey_wave_quater  Survey_wave_months Survey_date Survey_date_dt  \
24832                   Q1       January-March    07/05/14     2014-05-07   
24833                   Q1       January-March    07/05/14     2014-05-07   
24834                   Q1       January-March    07/05/14     2014-05-07   
24835                   Q1       January-March    07/05/14     2014-05-07   
24836             

In [21]:
# Replace missing quarters in the Quarter column with quarters from Survey_wave_quater column.
L_centr_fnl_0['Quarter'] = np.where((L_centr_fnl_0['Survey_wave_quater'] !=  L_centr_fnl_0['Quarter']) & 
                                 (L_centr_fnl_0['Quarter'] == ''), 
                                 L_centr_fnl_0['Survey_wave_quater'],
                                 L_centr_fnl_0['Quarter'])

# Check the output.
L_centr_fnl_0[L_centr_fnl_0['Quarter'] == '']

Empty DataFrame
Columns: [Survey wave (calendar quarter), Equivalent financial quarter, Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of private cycles, Number of cycle hire bikes, Total cycles, Survey_wave_year, Survey_wave_quater, Survey_wave_months, Survey_date, Survey_date_dt, Year, Month, Quarter]
Index: []

[0 rows x 22 columns]

In [22]:
# Combine year and quarter in one column and divide by '-'.
L_centr_fnl_0['Year-Quarter'] = L_centr_fnl_0['Year'].astype(str) + '-' + L_centr_fnl_0['Quarter'].astype(str)
L_centr_fnl_0.head()

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
0        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
1        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
2        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
3        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
4        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   

                             Location    Survey date Weather         Time  \
0  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0600 - 0615   
1  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0615 - 0630   
2  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0630 - 0645   
3  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0645 - 0700   
4  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0700 - 0715   

                        Period   Direction  Start hour  ...  Total cycles  \
0  Early Morning (06:00-07:00)  Northbound         6.0  ...           0.0   
1  Early Morning (06:00-07:00)  Northbound         6.0  ...          15.0   
2  Early Morning (06:00-07:00)  Northbound         6.0  ...          35.0   
3  Early Morning (06:00-07:00)  Northbound         6.0  ...          61.0   
4        AM peak (07:00-10:00)  Northbound         7.0  ...          73.0   

   Survey_wave_year  Survey_wave_quater  Survey_wave_months  Survey_date  \
0              2014                  Q1       January-March     24/01/14   
1              2014                  Q1       January-March     24/01/14   
2              2014                  Q1       January-March     24/01/14   
3              2014                  Q1       January-March     24/01/14   
4              2014                  Q1       January-March     24/01/14   

  Survey_date_dt  Year    Month Quarter  Year-Quarter  
0     2014-01-24  2014  January      Q1       2014-Q1  
1     2014-01-24  2014  January      Q1       2014-Q1  
2     2014-01-24  2014  January      Q1       2014-Q1  
3     2014-01-24  2014  January      Q1       2014-Q1  
4     2014-01-24  2014  January      Q1       2014-Q1  

[5 rows x 23 columns]

In [23]:
# Check if Time periods are in line with Period column for Early Morning (06:00-07:00).
EM = L_centr_fnl_0[L_centr_fnl_0['Period'] == 'Early Morning (06:00-07:00)']

EM[(EM['Time'] != '0600 - 0615') & (EM['Time'] != '0615 - 0630') & (EM['Time'] != '0630 - 0645') &
  (EM['Time'] != '0645 - 0700')]

Empty DataFrame
Columns: [Survey wave (calendar quarter), Equivalent financial quarter, Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of private cycles, Number of cycle hire bikes, Total cycles, Survey_wave_year, Survey_wave_quater, Survey_wave_months, Survey_date, Survey_date_dt, Year, Month, Quarter, Year-Quarter]
Index: []

[0 rows x 23 columns]

In [24]:
# Check if Time periods are in line with Period column for AM peak (07:00-10:00).
AP = L_centr_fnl_0[L_centr_fnl_0['Period'] == 'AM peak (07:00-10:00)']

AP[(AP['Time'] != '0700 - 0715') & (AP['Time'] != '0715 - 0730') & (AP['Time'] != '0730 - 0745') &
  (AP['Time'] != '0745 - 0800') & (AP['Time'] != '0800 - 0815') & (AP['Time'] != '0815 - 0830') & 
   (AP['Time'] != '0830 - 0845') & (AP['Time'] != '0845 - 0900') & (AP['Time'] != '0900 - 0915') & 
   (AP['Time'] != '0915 - 0930') & (AP['Time'] != '0930 - 0945') & (AP['Time'] != '0945 - 1000')]

Empty DataFrame
Columns: [Survey wave (calendar quarter), Equivalent financial quarter, Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of private cycles, Number of cycle hire bikes, Total cycles, Survey_wave_year, Survey_wave_quater, Survey_wave_months, Survey_date, Survey_date_dt, Year, Month, Quarter, Year-Quarter]
Index: []

[0 rows x 23 columns]

In [25]:
# Check if Time periods are in line with Period column for Inter-peak (10:00-16:00).
IP = L_centr_fnl_0[L_centr_fnl_0['Period'] == 'Inter-peak (10:00-16:00)']

IP[(IP['Time'] != '1000 - 1015') & (IP['Time'] != '1015 - 1030') & (IP['Time'] != '1030 - 1045') &
  (IP['Time'] != '1045 - 1100') & (IP['Time'] != '1100 - 1115') & (IP['Time'] != '1115 - 1130') & 
   (IP['Time'] != '1130 - 1145') & (IP['Time'] != '1145 - 1200') & (IP['Time'] != '1200 - 1215') & 
   (IP['Time'] != '1215 - 1230') & (IP['Time'] != '1230 - 1245') & (IP['Time'] != '1245 - 1300') &
  (IP['Time'] != '1300 - 1315') & (IP['Time'] != '1315 - 1330') & (IP['Time'] != '1330 - 1345') &
  (IP['Time'] != '1345 - 1400') & (IP['Time'] != '1400 - 1415') & (IP['Time'] != '1415 - 1430') & 
   (IP['Time'] != '1430 - 1445') & (IP['Time'] != '1445 - 1500') & (IP['Time'] != '1500 - 1515') & 
   (IP['Time'] != '1515 - 1530') & (IP['Time'] != '1530 - 1545') & (IP['Time'] != '1545 - 1600')]

Empty DataFrame
Columns: [Survey wave (calendar quarter), Equivalent financial quarter, Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of private cycles, Number of cycle hire bikes, Total cycles, Survey_wave_year, Survey_wave_quater, Survey_wave_months, Survey_date, Survey_date_dt, Year, Month, Quarter, Year-Quarter]
Index: []

[0 rows x 23 columns]

In [26]:
# Check if Time periods are in line with Period column for PM peak (16:00-19:00).
PP = L_centr_fnl_0[L_centr_fnl_0['Period'] == 'PM peak (16:00-19:00)']

PP[(PP['Time'] != '1600 - 1615') & (PP['Time'] != '1615 - 1630') & (PP['Time'] != '1630 - 1645') &
  (PP['Time'] != '1645 - 1700') & (PP['Time'] != '1700 - 1715') & (PP['Time'] != '1715 - 1730') & 
   (PP['Time'] != '1730 - 1745') & (PP['Time'] != '1745 - 1800') & (PP['Time'] != '1800 - 1815') & 
   (PP['Time'] != '1815 - 1830') & (PP['Time'] != '1830 - 1845') & (PP['Time'] != '1845 - 1900')]

Empty DataFrame
Columns: [Survey wave (calendar quarter), Equivalent financial quarter, Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of private cycles, Number of cycle hire bikes, Total cycles, Survey_wave_year, Survey_wave_quater, Survey_wave_months, Survey_date, Survey_date_dt, Year, Month, Quarter, Year-Quarter]
Index: []

[0 rows x 23 columns]

In [27]:
# Check if Time periods are in line with Period column for Evening (19:00-22:00).
E = L_centr_fnl_0[L_centr_fnl_0['Period'] == 'Evening (19:00-22:00)']

E[(E['Time'] != '1900 - 1915') & (E['Time'] != '1915 - 1930') & (E['Time'] != '1930 - 1945') &
  (E['Time'] != '1945 - 2000') & (E['Time'] != '2000 - 2015') & (E['Time'] != '2015 - 2030') & 
   (E['Time'] != '2030 - 2045') & (E['Time'] != '2045 - 2100') & (E['Time'] != '2100 - 2115') & 
   (E['Time'] != '2115 - 2130') & (E['Time'] != '2130 - 2145') & (E['Time'] != '2145 - 2200')]

Empty DataFrame
Columns: [Survey wave (calendar quarter), Equivalent financial quarter, Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of private cycles, Number of cycle hire bikes, Total cycles, Survey_wave_year, Survey_wave_quater, Survey_wave_months, Survey_date, Survey_date_dt, Year, Month, Quarter, Year-Quarter]
Index: []

[0 rows x 23 columns]

In [28]:
# Check missing values.
L_centr_fnl_0.isnull().sum()

Survey wave (calendar quarter)        0
Equivalent financial quarter          0
Site ID                               0
Location                              0
Survey date                       10412
Weather                           11834
Time                                  0
Period                                0
Direction                             0
Start hour                            0
Start minute                          0
Number of private cycles             64
Number of cycle hire bikes           64
Total cycles                          0
Survey_wave_year                      0
Survey_wave_quater                    0
Survey_wave_months                    0
Survey_date                       10412
Survey_date_dt                    10412
Year                                  0
Month                             10412
Quarter                               0
Year-Quarter                          0
dtype: int64

In [29]:
# Check dtypes.
L_centr_fnl_0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 758163 entries, 0 to 758162
Data columns (total 23 columns):
 #   Column                          Non-Null Count   Dtype         
---  ------                          --------------   -----         
 0   Survey wave (calendar quarter)  758163 non-null  object        
 1   Equivalent financial quarter    758163 non-null  object        
 2   Site ID                         758163 non-null  object        
 3   Location                        758163 non-null  object        
 4   Survey date                     747751 non-null  object        
 5   Weather                         746329 non-null  object        
 6   Time                            758163 non-null  object        
 7   Period                          758163 non-null  object        
 8   Direction                       758163 non-null  object        
 9   Start hour                      758163 non-null  float64       
 10  Start minute                    758163 non-null  float64

### Missing values in Date and Time related columns

In [30]:
# Select rows containing missing values in 'Survey_date_dt' column.
L_centr_fnl_1 = L_centr_fnl_0[L_centr_fnl_0['Survey_date_dt'].isnull()]

# View DataFrame.
L_centr_fnl_1.head()

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
114368        2015 Q1 (January-March)                   2014-15 Q4  CENCY094   
114369        2015 Q1 (January-March)                   2014-15 Q4  CENCY094   
114370        2015 Q1 (January-March)                   2014-15 Q4  CENCY094   
114371        2015 Q1 (January-March)                   2014-15 Q4  CENCY094   
114372        2015 Q1 (January-March)                   2014-15 Q4  CENCY094   

           Location Survey date Weather         Time  \
114368  Houndsditch         NaN     NaN  0600 - 0615   
114369  Houndsditch         NaN     NaN  0615 - 0630   
114370  Houndsditch         NaN     NaN  0630 - 0645   
114371  Houndsditch         NaN     NaN  0645 - 0700   
114372  Houndsditch         NaN     NaN  0700 - 0715   

                             Period  Direction  Start hour  ...  Total cycles  \
114368  Early Morning (06:00-07:00)  Eastbound         6.0  ...           3.0   
114369  Early Morning (06:00-07:00)  Eastbound         6.0  ...           3.0   
114370  Early Morning (06:00-07:00)  Eastbound         6.0  ...           2.0   
114371  Early Morning (06:00-07:00)  Eastbound         6.0  ...           2.0   
114372        AM peak (07:00-10:00)  Eastbound         7.0  ...           6.0   

        Survey_wave_year  Survey_wave_quater  Survey_wave_months  Survey_date  \
114368              2015                  Q1       January-March          NaN   
114369              2015                  Q1       January-March          NaN   
114370              2015                  Q1       January-March          NaN   
114371              2015                  Q1       January-March          NaN   
114372              2015                  Q1       January-March          NaN   

       Survey_date_dt  Year Month Quarter  Year-Quarter  
114368            NaT  2015   NaN      Q1       2015-Q1  
114369            NaT  2015   NaN      Q1       2015-Q1  
114370            NaT  2015   NaN      Q1       2015-Q1  
114371            NaT  2015   NaN      Q1       2015-Q1  
114372            NaT  2015   NaN      Q1       2015-Q1  

[5 rows x 23 columns]

In [31]:
# View number of missing values in 'Survey_date_dt' column by calendar quarter.
L_centr_fnl_1['Year-Quarter'].value_counts().sort_index()

2015-Q1     512
2015-Q2     256
2015-Q3    1024
2015-Q4     256
2016-Q1     256
2016-Q2     384
2016-Q3     384
2017-Q1     128
2017-Q2     768
2017-Q3     128
2017-Q4    1280
2018-Q1     512
2018-Q2     896
2020-Q1    3200
2020-Q3     428
Name: Year-Quarter, dtype: int64

In [32]:
# Select rows without missing values in 'Survey_date_dt' column.
L_centr_fnl_2 = L_centr_fnl_0[~L_centr_fnl_0['Survey_date_dt'].isnull()]

# View DataFrame.
L_centr_fnl_2.head()

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
0        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
1        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
2        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
3        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
4        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   

                             Location    Survey date Weather         Time  \
0  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0600 - 0615   
1  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0615 - 0630   
2  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0630 - 0645   
3  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0645 - 0700   
4  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0700 - 0715   

                        Period   Direction  Start hour  ...  Total cycles  \
0  Early Morning (06:00-07:00)  Northbound         6.0  ...           0.0   
1  Early Morning (06:00-07:00)  Northbound         6.0  ...          15.0   
2  Early Morning (06:00-07:00)  Northbound         6.0  ...          35.0   
3  Early Morning (06:00-07:00)  Northbound         6.0  ...          61.0   
4        AM peak (07:00-10:00)  Northbound         7.0  ...          73.0   

   Survey_wave_year  Survey_wave_quater  Survey_wave_months  Survey_date  \
0              2014                  Q1       January-March     24/01/14   
1              2014                  Q1       January-March     24/01/14   
2              2014                  Q1       January-March     24/01/14   
3              2014                  Q1       January-March     24/01/14   
4              2014                  Q1       January-March     24/01/14   

  Survey_date_dt  Year    Month Quarter  Year-Quarter  
0     2014-01-24  2014  January      Q1       2014-Q1  
1     2014-01-24  2014  January      Q1       2014-Q1  
2     2014-01-24  2014  January      Q1       2014-Q1  
3     2014-01-24  2014  January      Q1       2014-Q1  
4     2014-01-24  2014  January      Q1       2014-Q1  

[5 rows x 23 columns]

In [33]:
# View number of values in 'Survey_date_dt' column by calendar quarter (excluding missing values).
L_centr_fnl_2['Year-Quarter'].value_counts().sort_index()

2014-Q1    25380
2014-Q2    25402
2014-Q3    24866
2014-Q4    26892
2015-Q1    25452
2015-Q2    25876
2015-Q3    24298
2015-Q4    25290
2016-Q1    26358
2016-Q2    24456
2016-Q3    24140
2016-Q4    26678
2017-Q1    26118
2017-Q2    23116
2017-Q3    27888
2017-Q4    25322
2018-Q1    26304
2018-Q2    26120
2018-Q3    25538
2018-Q4    27338
2019-Q1    28928
2019-Q2    25028
2019-Q3    26412
2019-Q4    26512
2020-Q1    23936
2020-Q2      470
2020-Q3    25930
2020-Q4       52
2021-Q2    24247
2021-Q3    27470
2021-Q4    25934
Name: Year-Quarter, dtype: int64

In [34]:
# Find first and last date in 'Survey_date_dt' column.
print(L_centr_fnl_0['Survey_date_dt'].min())
print(L_centr_fnl_0['Survey_date_dt'].max())

# View frequency of dates.
L_centr_fnl_0['Survey_date_dt'].value_counts()

2014-01-20 00:00:00
2021-12-30 00:00:00


2014-01-30    2690
2014-02-03    2330
2014-01-31    2207
2014-01-29    2185
2014-01-28    1874
              ... 
2021-12-30      14
2018-02-13       8
2014-07-07       8
2019-07-26       8
2019-05-27       2
Name: Survey_date_dt, Length: 1596, dtype: int64

In [35]:
# View frequency of location.
L_centr_fnl_0['Location'].value_counts()

Regent Street                    7424
Charing Cross Road               7424
Borough High Street              7296
Southwark Street                 7168
Lambeth Road                     5504
                                 ... 
Pakenham Street                  1792
Tooley Street (east)             1664
Southwark Bridge Road (south)    1664
Princess Street                  1664
Sidmouth Square                  1536
Name: Location, Length: 205, dtype: int64

### Investigate missing dates related to Regent Street location

#### 2016

In [36]:
# Select rows with location 'Regent Street' and missing values in 'Survey_date_dt' column.
Rst_0 = L_centr_fnl_0[(L_centr_fnl_0['Location'] == 'Regent Street') & (L_centr_fnl_0['Survey_date_dt'].isnull())]

Rst_0

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
282176       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282177       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282178       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282179       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282180       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
...                               ...                          ...       ...   
282299       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282300       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282301       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282302       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282303       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   

             Location Survey date Weather         Time  \
282176  Regent Street         NaN     NaN  0600 - 0615   
282177  Regent Street         NaN     NaN  0615 - 0630   
282178  Regent Street         NaN     NaN  0630 - 0645   
282179  Regent Street         NaN     NaN  0645 - 0700   
282180  Regent Street         NaN     NaN  0700 - 0715   
...               ...         ...     ...          ...   
282299  Regent Street         NaN     NaN  2045 - 2100   
282300  Regent Street         NaN     NaN  2100 - 2115   
282301  Regent Street         NaN     NaN  2115 - 2130   
282302  Regent Street         NaN     NaN  2130 - 2145   
282303  Regent Street         NaN     NaN  2145 - 2200   

                             Period   Direction  Start hour  ...  \
282176  Early Morning (06:00-07:00)  Northbound         6.0  ...   
282177  Early Morning (06:00-07:00)  Northbound         6.0  ...   
282178  Early Morning (06:00-07:00)  Northbound         6.0  ...   
282179  Early Morning (06:00-07:00)  Northbound         6.0  ...   
282180        AM peak (07:00-10:00)  Northbound         7.0  ...   
...                             ...         ...         ...  ...   
282299        Evening (19:00-22:00)  Southbound        20.0  ...   
282300        Evening (19:00-22:00)  Southbound        21.0  ...   
282301        Evening (19:00-22:00)  Southbound        21.0  ...   
282302        Evening (19:00-22:00)  Southbound        21.0  ...   
282303        Evening (19:00-22:00)  Southbound        21.0  ...   

        Total cycles  Survey_wave_year  Survey_wave_quater  \
282176           7.0              2016                  Q3   
282177           8.0              2016                  Q3   
282178          16.0              2016                  Q3   
282179          13.0              2016                  Q3   
282180          12.0              2016                  Q3   
...              ...               ...                 ...   
282299           0.0              2016                  Q3   
282300           0.0              2016                  Q3   
282301           1.0              2016                  Q3   
282302           0.0              2016                  Q3   
282303           0.0              2016                  Q3   

        Survey_wave_months  Survey_date Survey_date_dt  Year Month Quarter  \
282176      July-September          NaN            NaT  2016   NaN      Q3   
282177      July-September          NaN            NaT  2016   NaN      Q3   
282178      July-September          NaN            NaT  2016   NaN      Q3   
282179      July-September          NaN            NaT  2016   NaN      Q3   
282180      July-September          NaN            NaT  2016   NaN      Q3   
...                    ...          ...            ...   ...   ...     ...   
282299      July-September          NaN            NaT  2016   NaN      Q3   
282300      July-September          NaN            NaT  2016   NaN      Q3   
282301      July-September          NaN            NaT  2016   NaN      Q3   
282302 

In [37]:
# Check missing values in 'Survey_date_dt' column by calendar quarter related to Regent Street location.
Rst_0['Year-Quarter'].value_counts()

# All missing dates related to Regent Street is within 2016 Q3.

2016-Q3    128
Name: Year-Quarter, dtype: int64

In [38]:
# Select rows from the main DataFrame with location 'Regent Street' and 'Year-Quarter' column == 2016 Q3.
Rst_16_Q3 = L_centr_fnl_0[(L_centr_fnl_0['Location'] == 'Regent Street') & 
                          (L_centr_fnl_0['Year-Quarter'] == '2016-Q3')].sort_index()

Rst_16_Q3

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
264768       2016 Q3 (July-September)                   2016-17 Q2  CENCY063   
264769       2016 Q3 (July-September)                   2016-17 Q2  CENCY063   
264770       2016 Q3 (July-September)                   2016-17 Q2  CENCY063   
264771       2016 Q3 (July-September)                   2016-17 Q2  CENCY063   
264772       2016 Q3 (July-September)                   2016-17 Q2  CENCY063   
...                               ...                          ...       ...   
282299       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282300       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282301       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282302       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282303       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   

             Location    Survey date Weather         Time  \
264768  Regent Street  ven, 09/09/16     Dry  0600 - 0615   
264769  Regent Street  ven, 09/09/16     Dry  0615 - 0630   
264770  Regent Street  ven, 09/09/16     Dry  0630 - 0645   
264771  Regent Street  ven, 09/09/16     Dry  0645 - 0700   
264772  Regent Street  ven, 09/09/16     Dry  0700 - 0715   
...               ...            ...     ...          ...   
282299  Regent Street            NaN     NaN  2045 - 2100   
282300  Regent Street            NaN     NaN  2100 - 2115   
282301  Regent Street            NaN     NaN  2115 - 2130   
282302  Regent Street            NaN     NaN  2130 - 2145   
282303  Regent Street            NaN     NaN  2145 - 2200   

                             Period   Direction  Start hour  ...  \
264768  Early Morning (06:00-07:00)  Northbound         6.0  ...   
264769  Early Morning (06:00-07:00)  Northbound         6.0  ...   
264770  Early Morning (06:00-07:00)  Northbound         6.0  ...   
264771  Early Morning (06:00-07:00)  Northbound         6.0  ...   
264772        AM peak (07:00-10:00)  Northbound         7.0  ...   
...                             ...         ...         ...  ...   
282299        Evening (19:00-22:00)  Southbound        20.0  ...   
282300        Evening (19:00-22:00)  Southbound        21.0  ...   
282301        Evening (19:00-22:00)  Southbound        21.0  ...   
282302        Evening (19:00-22:00)  Southbound        21.0  ...   
282303        Evening (19:00-22:00)  Southbound        21.0  ...   

        Total cycles  Survey_wave_year  Survey_wave_quater  \
264768           1.0              2016                  Q3   
264769           2.0              2016                  Q3   
264770          10.0              2016                  Q3   
264771          15.0              2016                  Q3   
264772          20.0              2016                  Q3   
...              ...               ...                 ...   
282299           0.0              2016                  Q3   
282300           0.0              2016                  Q3   
282301           1.0              2016                  Q3   
282302           0.0              2016                  Q3   
282303           0.0              2016                  Q3   

        Survey_wave_months  Survey_date Survey_date_dt  Year      Month  \
264768      July-September     09/09/16     2016-09-09  2016  September   
264769      July-September     09/09/16     2016-09-09  2016  September   
264770      July-September     09/09/16     2016-09-09  2016  September   
264771      July-September     09/09/16     2016-09-09  2016  September   
264772      July-September     09/09/16     2016-09-09  2016  September   
...                    ...          ...            ...   ...        ...   
282299      July-September          NaN            NaT  2016        NaN   
282300      July-September          NaN            NaT  2016        NaN   
282301      July-September          NaN            NaT  2016        NaN   
2

In [39]:
# Check dates related to the flollowing rows after 282303 and 2016 Q3.
L_centr_fnl_0.loc[(L_centr_fnl_0.index > 282303) & 
                  (L_centr_fnl_0['Year-Quarter'] == '2016-Q3')]

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
282304       2016 Q3 (July-September)                   2016-17 Q2  CENCY702   
282305       2016 Q3 (July-September)                   2016-17 Q2  CENCY702   
282306       2016 Q3 (July-September)                   2016-17 Q2  CENCY702   
282307       2016 Q3 (July-September)                   2016-17 Q2  CENCY702   
282308       2016 Q3 (July-September)                   2016-17 Q2  CENCY702   
...                               ...                          ...       ...   
282427       2016 Q3 (July-September)                   2016-17 Q2  CENCY702   
282428       2016 Q3 (July-September)                   2016-17 Q2  CENCY702   
282429       2016 Q3 (July-September)                   2016-17 Q2  CENCY702   
282430       2016 Q3 (July-September)                   2016-17 Q2  CENCY702   
282431       2016 Q3 (July-September)                   2016-17 Q2  CENCY702   

         Location    Survey date Weather         Time  \
282304  Haymarket  lun, 19/09/16    Fine  0600 - 0615   
282305  Haymarket  lun, 19/09/16    Fine  0615 - 0630   
282306  Haymarket  lun, 19/09/16    Fine  0630 - 0645   
282307  Haymarket  lun, 19/09/16    Fine  0645 - 0700   
282308  Haymarket  lun, 19/09/16    Fine  0700 - 0715   
...           ...            ...     ...          ...   
282427  Haymarket  mar, 13/09/16    Fine  2045 - 2100   
282428  Haymarket  mar, 13/09/16    Fine  2100 - 2115   
282429  Haymarket  mar, 13/09/16    Fine  2115 - 2130   
282430  Haymarket  mar, 13/09/16    Fine  2130 - 2145   
282431  Haymarket  mar, 13/09/16    Fine  2145 - 2200   

                             Period   Direction  Start hour  ...  \
282304  Early Morning (06:00-07:00)  Northbound         6.0  ...   
282305  Early Morning (06:00-07:00)  Northbound         6.0  ...   
282306  Early Morning (06:00-07:00)  Northbound         6.0  ...   
282307  Early Morning (06:00-07:00)  Northbound         6.0  ...   
282308        AM peak (07:00-10:00)  Northbound         7.0  ...   
...                             ...         ...         ...  ...   
282427        Evening (19:00-22:00)  Southbound        20.0  ...   
282428        Evening (19:00-22:00)  Southbound        21.0  ...   
282429        Evening (19:00-22:00)  Southbound        21.0  ...   
282430        Evening (19:00-22:00)  Southbound        21.0  ...   
282431        Evening (19:00-22:00)  Southbound        21.0  ...   

        Total cycles  Survey_wave_year  Survey_wave_quater  \
282304           0.0              2016                  Q3   
282305           0.0              2016                  Q3   
282306           0.0              2016                  Q3   
282307           1.0              2016                  Q3   
282308           2.0              2016                  Q3   
...              ...               ...                 ...   
282427          31.0              2016                  Q3   
282428          27.0              2016                  Q3   
282429          24.0              2016                  Q3   
282430          26.0              2016                  Q3   
282431          20.0              2016                  Q3   

        Survey_wave_months  Survey_date Survey_date_dt  Year      Month  \
282304      July-September     19/09/16     2016-09-19  2016  September   
282305      July-September     19/09/16     2016-09-19  2016  September   
282306      July-September     19/09/16     2016-09-19  2016  September   
282307      July-September     19/09/16     2016-09-19  2016  September   
282308      July-September     19/09/16     2016-09-19  2016  September   
...                    ...          ...            ...   ...        ...   
282427      July-September     13/09/16     2016-09-13  2016  September   
282428      July-September     13/09/16     2016-09-13  2016  September   
282429      July-September     13/09/16     2016-09-13  2016  September   
282430      July-September     13/09/16     2016-

In [40]:
# View frequency of dates in 'Survey_date_dt' column.
Rst_16_Q3['Survey_date_dt'].value_counts()

2016-09-09    64
2016-09-08    64
Name: Survey_date_dt, dtype: int64

In [41]:
# Check dates related to CENCY063 site ID in 2016 Q1.
Rst_16_Q3.loc[Rst_16_Q3['Site ID'] == 'CENCY063']['Survey_date_dt'].value_counts(sort=False)

2016-09-09    64
2016-09-08    64
Name: Survey_date_dt, dtype: int64

In [42]:
# View frequency of time slots in 'Time' column.
Rst_16_Q3['Time'].value_counts()

0600 - 0615    4
0615 - 0630    4
1430 - 1445    4
1445 - 1500    4
1500 - 1515    4
              ..
1230 - 1245    4
1245 - 1300    4
1300 - 1315    4
1315 - 1330    4
2145 - 2200    4
Name: Time, Length: 64, dtype: int64

In [43]:
# View frequency of sites in 'Site ID' column.
Rst_16_Q3['Site ID'].value_counts()

CENCY063    128
CENCY701    128
Name: Site ID, dtype: int64

In [44]:
# Check missing values in 2016 Q3 for CENCY063 site ID.
Rst_16_Q3.loc[(Rst_16_Q3['Site ID'] == 'CENCY063') & (Rst_16_Q3['Survey_date_dt'].isnull())]

Empty DataFrame
Columns: [Survey wave (calendar quarter), Equivalent financial quarter, Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of private cycles, Number of cycle hire bikes, Total cycles, Survey_wave_year, Survey_wave_quater, Survey_wave_months, Survey_date, Survey_date_dt, Year, Month, Quarter, Year-Quarter]
Index: []

[0 rows x 23 columns]

In [45]:
# Check missing values in 2016 Q3 for CENCY701 site ID.
Rst_16_Q3.loc[(Rst_16_Q3['Site ID'] == 'CENCY701') & (Rst_16_Q3['Survey_date_dt'].isnull())]

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
282176       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282177       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282178       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282179       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282180       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
...                               ...                          ...       ...   
282299       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282300       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282301       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282302       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   
282303       2016 Q3 (July-September)                   2016-17 Q2  CENCY701   

             Location Survey date Weather         Time  \
282176  Regent Street         NaN     NaN  0600 - 0615   
282177  Regent Street         NaN     NaN  0615 - 0630   
282178  Regent Street         NaN     NaN  0630 - 0645   
282179  Regent Street         NaN     NaN  0645 - 0700   
282180  Regent Street         NaN     NaN  0700 - 0715   
...               ...         ...     ...          ...   
282299  Regent Street         NaN     NaN  2045 - 2100   
282300  Regent Street         NaN     NaN  2100 - 2115   
282301  Regent Street         NaN     NaN  2115 - 2130   
282302  Regent Street         NaN     NaN  2130 - 2145   
282303  Regent Street         NaN     NaN  2145 - 2200   

                             Period   Direction  Start hour  ...  \
282176  Early Morning (06:00-07:00)  Northbound         6.0  ...   
282177  Early Morning (06:00-07:00)  Northbound         6.0  ...   
282178  Early Morning (06:00-07:00)  Northbound         6.0  ...   
282179  Early Morning (06:00-07:00)  Northbound         6.0  ...   
282180        AM peak (07:00-10:00)  Northbound         7.0  ...   
...                             ...         ...         ...  ...   
282299        Evening (19:00-22:00)  Southbound        20.0  ...   
282300        Evening (19:00-22:00)  Southbound        21.0  ...   
282301        Evening (19:00-22:00)  Southbound        21.0  ...   
282302        Evening (19:00-22:00)  Southbound        21.0  ...   
282303        Evening (19:00-22:00)  Southbound        21.0  ...   

        Total cycles  Survey_wave_year  Survey_wave_quater  \
282176           7.0              2016                  Q3   
282177           8.0              2016                  Q3   
282178          16.0              2016                  Q3   
282179          13.0              2016                  Q3   
282180          12.0              2016                  Q3   
...              ...               ...                 ...   
282299           0.0              2016                  Q3   
282300           0.0              2016                  Q3   
282301           1.0              2016                  Q3   
282302           0.0              2016                  Q3   
282303           0.0              2016                  Q3   

        Survey_wave_months  Survey_date Survey_date_dt  Year Month Quarter  \
282176      July-September          NaN            NaT  2016   NaN      Q3   
282177      July-September          NaN            NaT  2016   NaN      Q3   
282178      July-September          NaN            NaT  2016   NaN      Q3   
282179      July-September          NaN            NaT  2016   NaN      Q3   
282180      July-September          NaN            NaT  2016   NaN      Q3   
...                    ...          ...            ...   ...   ...     ...   
282299      July-September          NaN            NaT  2016   NaN      Q3   
282300      July-September          NaN            NaT  2016   NaN      Q3   
282301      July-September          NaN            NaT  2016   NaN      Q3   
282302 

In [46]:
# Check how many site IDs are asigned to Regent Street location.
Rst = L_centr_fnl_0.loc[L_centr_fnl_0['Location'] == 'Regent Street']
print(Rst['Site ID'].value_counts())

# View DataFrame.
Rst.head()

CENCY063    3712
CENCY701    3712
Name: Site ID, dtype: int64


Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
7936        2014 Q1 (January-March)                   2013-14 Q4  CENCY063   
7937        2014 Q1 (January-March)                   2013-14 Q4  CENCY063   
7938        2014 Q1 (January-March)                   2013-14 Q4  CENCY063   
7939        2014 Q1 (January-March)                   2013-14 Q4  CENCY063   
7940        2014 Q1 (January-March)                   2013-14 Q4  CENCY063   

           Location    Survey date Weather         Time  \
7936  Regent Street  mar, 28/01/14    Fine  0600 - 0615   
7937  Regent Street  mar, 28/01/14    Fine  0615 - 0630   
7938  Regent Street  mar, 28/01/14    Fine  0630 - 0645   
7939  Regent Street  mar, 28/01/14    Fine  0645 - 0700   
7940  Regent Street  mar, 28/01/14    Fine  0700 - 0715   

                           Period   Direction  Start hour  ...  Total cycles  \
7936  Early Morning (06:00-07:00)  Northbound         6.0  ...           1.0   
7937  Early Morning (06:00-07:00)  Northbound         6.0  ...           2.0   
7938  Early Morning (06:00-07:00)  Northbound         6.0  ...           8.0   
7939  Early Morning (06:00-07:00)  Northbound         6.0  ...           5.0   
7940        AM peak (07:00-10:00)  Northbound         7.0  ...           5.0   

      Survey_wave_year  Survey_wave_quater  Survey_wave_months  Survey_date  \
7936              2014                  Q1       January-March     28/01/14   
7937              2014                  Q1       January-March     28/01/14   
7938              2014                  Q1       January-March     28/01/14   
7939              2014                  Q1       January-March     28/01/14   
7940              2014                  Q1       January-March     28/01/14   

     Survey_date_dt  Year    Month Quarter  Year-Quarter  
7936     2014-01-28  2014  January      Q1       2014-Q1  
7937     2014-01-28  2014  January      Q1       2014-Q1  
7938     2014-01-28  2014  January      Q1       2014-Q1  
7939     2014-01-28  2014  January      Q1       2014-Q1  
7940     2014-01-28  2014  January      Q1       2014-Q1  

[5 rows x 23 columns]

In [47]:
# Select rows related to 2016 Q1.
Rst_16_Q1 = Rst.loc[Rst['Year-Quarter'] == '2016-Q1'].sort_index() 

# View DataFrame.
Rst_16_Q1

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
213440        2016 Q1 (January-March)                   2015-16 Q4  CENCY063   
213441        2016 Q1 (January-March)                   2015-16 Q4  CENCY063   
213442        2016 Q1 (January-March)                   2015-16 Q4  CENCY063   
213443        2016 Q1 (January-March)                   2015-16 Q4  CENCY063   
213444        2016 Q1 (January-March)                   2015-16 Q4  CENCY063   
...                               ...                          ...       ...   
230971        2016 Q1 (January-March)                   2015-16 Q4  CENCY701   
230972        2016 Q1 (January-March)                   2015-16 Q4  CENCY701   
230973        2016 Q1 (January-March)                   2015-16 Q4  CENCY701   
230974        2016 Q1 (January-March)                   2015-16 Q4  CENCY701   
230975        2016 Q1 (January-March)                   2015-16 Q4  CENCY701   

             Location    Survey date Weather         Time  \
213440  Regent Street  mar, 22/03/16    Fine  0600 - 0615   
213441  Regent Street  mar, 22/03/16    Fine  0615 - 0630   
213442  Regent Street  mar, 22/03/16    Fine  0630 - 0645   
213443  Regent Street  mar, 22/03/16    Fine  0645 - 0700   
213444  Regent Street  mar, 22/03/16    Fine  0700 - 0715   
...               ...            ...     ...          ...   
230971  Regent Street  mer, 10/02/16    Fine  2045 - 2100   
230972  Regent Street  mer, 10/02/16    Fine  2100 - 2115   
230973  Regent Street  mer, 10/02/16    Fine  2115 - 2130   
230974  Regent Street  mer, 10/02/16    Fine  2130 - 2145   
230975  Regent Street  mer, 10/02/16    Fine  2145 - 2200   

                             Period   Direction  Start hour  ...  \
213440  Early Morning (06:00-07:00)  Northbound         6.0  ...   
213441  Early Morning (06:00-07:00)  Northbound         6.0  ...   
213442  Early Morning (06:00-07:00)  Northbound         6.0  ...   
213443  Early Morning (06:00-07:00)  Northbound         6.0  ...   
213444        AM peak (07:00-10:00)  Northbound         7.0  ...   
...                             ...         ...         ...  ...   
230971        Evening (19:00-22:00)  Southbound        20.0  ...   
230972        Evening (19:00-22:00)  Southbound        21.0  ...   
230973        Evening (19:00-22:00)  Southbound        21.0  ...   
230974        Evening (19:00-22:00)  Southbound        21.0  ...   
230975        Evening (19:00-22:00)  Southbound        21.0  ...   

        Total cycles  Survey_wave_year  Survey_wave_quater  \
213440           2.0              2016                  Q1   
213441           9.0              2016                  Q1   
213442          11.0              2016                  Q1   
213443          20.0              2016                  Q1   
213444          15.0              2016                  Q1   
...              ...               ...                 ...   
230971           2.0              2016                  Q1   
230972           0.0              2016                  Q1   
230973           1.0              2016                  Q1   
230974           2.0              2016                  Q1   
230975           0.0              2016                  Q1   

        Survey_wave_months  Survey_date Survey_date_dt  Year     Month  \
213440       January-March     22/03/16     2016-03-22  2016     March   
213441       January-March     22/03/16     2016-03-22  2016     March   
213442       January-March     22/03/16     2016-03-22  2016     March   
213443       January-March     22/03/16     2016-03-22  2016     March   
213444       January-March     22/03/16     2016-03-22  2016     March   
...                    ...          ...            ...   ...       ...   
230971       January-March     10/02/16     2016-02-10  2016  February   
230972       January-March     10/02/16     2016-02-10  2016  February   
230973       January-March     10/02/16     2016-02-10  2016  February   
230974     

In [48]:
# View frequency of dates in 'Survey_date_dt' column.
Rst_16_Q1['Survey_date_dt'].value_counts()

2016-03-22    64
2016-03-16    64
2016-02-09    64
2016-02-10    64
Name: Survey_date_dt, dtype: int64

In [49]:
# View frequency of sites in 'Site ID' column.
Rst_16_Q1['Site ID'].value_counts()

CENCY063    128
CENCY701    128
Name: Site ID, dtype: int64

In [50]:
# View frequency of time slots in 'Time' column.
Rst_16_Q1['Time'].value_counts()

0600 - 0615    4
0615 - 0630    4
1430 - 1445    4
1445 - 1500    4
1500 - 1515    4
              ..
1230 - 1245    4
1245 - 1300    4
1300 - 1315    4
1315 - 1330    4
2145 - 2200    4
Name: Time, Length: 64, dtype: int64

In [51]:
# Check dates related to CENCY063 site ID in 2016 Q1.
Rst_16_Q1.loc[Rst_16_Q1['Site ID'] == 'CENCY063']['Survey_date_dt'].value_counts(sort=False)

2016-03-22    64
2016-03-16    64
Name: Survey_date_dt, dtype: int64

In [52]:
# Select rows related to 2016 Q2.
Rst_16_Q2 = Rst.loc[Rst['Year-Quarter'] == '2016-Q2'] 

# View DataFrame.
Rst_16_Q2

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
239040           2016 Q2 (April-June)                   2016-17 Q1  CENCY063   
239041           2016 Q2 (April-June)                   2016-17 Q1  CENCY063   
239042           2016 Q2 (April-June)                   2016-17 Q1  CENCY063   
239043           2016 Q2 (April-June)                   2016-17 Q1  CENCY063   
239044           2016 Q2 (April-June)                   2016-17 Q1  CENCY063   
...                               ...                          ...       ...   
256699           2016 Q2 (April-June)                   2016-17 Q1  CENCY701   
256700           2016 Q2 (April-June)                   2016-17 Q1  CENCY701   
256701           2016 Q2 (April-June)                   2016-17 Q1  CENCY701   
256702           2016 Q2 (April-June)                   2016-17 Q1  CENCY701   
256703           2016 Q2 (April-June)                   2016-17 Q1  CENCY701   

             Location    Survey date Weather         Time  \
239040  Regent Street  mer, 22/06/16     Dry  0600 - 0615   
239041  Regent Street  mer, 22/06/16     Dry  0615 - 0630   
239042  Regent Street  mer, 22/06/16     Dry  0630 - 0645   
239043  Regent Street  mer, 22/06/16     Dry  0645 - 0700   
239044  Regent Street  mer, 22/06/16     Dry  0700 - 0715   
...               ...            ...     ...          ...   
256699  Regent Street  ven, 29/04/16     Dry  2045 - 2100   
256700  Regent Street  ven, 29/04/16     Dry  2100 - 2115   
256701  Regent Street  ven, 29/04/16     Dry  2115 - 2130   
256702  Regent Street  ven, 29/04/16     Dry  2130 - 2145   
256703  Regent Street  ven, 29/04/16     Dry  2145 - 2200   

                             Period   Direction  Start hour  ...  \
239040  Early Morning (06:00-07:00)  Northbound         6.0  ...   
239041  Early Morning (06:00-07:00)  Northbound         6.0  ...   
239042  Early Morning (06:00-07:00)  Northbound         6.0  ...   
239043  Early Morning (06:00-07:00)  Northbound         6.0  ...   
239044        AM peak (07:00-10:00)  Northbound         7.0  ...   
...                             ...         ...         ...  ...   
256699        Evening (19:00-22:00)  Southbound        20.0  ...   
256700        Evening (19:00-22:00)  Southbound        21.0  ...   
256701        Evening (19:00-22:00)  Southbound        21.0  ...   
256702        Evening (19:00-22:00)  Southbound        21.0  ...   
256703        Evening (19:00-22:00)  Southbound        21.0  ...   

        Total cycles  Survey_wave_year  Survey_wave_quater  \
239040           5.0              2016                  Q2   
239041           4.0              2016                  Q2   
239042          11.0              2016                  Q2   
239043          14.0              2016                  Q2   
239044          19.0              2016                  Q2   
...              ...               ...                 ...   
256699           0.0              2016                  Q2   
256700           0.0              2016                  Q2   
256701           0.0              2016                  Q2   
256702           0.0              2016                  Q2   
256703           0.0              2016                  Q2   

        Survey_wave_months  Survey_date Survey_date_dt  Year  Month Quarter  \
239040          April-June     22/06/16     2016-06-22  2016   June      Q2   
239041          April-June     22/06/16     2016-06-22  2016   June      Q2   
239042          April-June     22/06/16     2016-06-22  2016   June      Q2   
239043          April-June     22/06/16     2016-06-22  2016   June      Q2   
239044          April-June     22/06/16     2016-06-22  2016   June      Q2   
...                    ...          ...            ...   ...    ...     ...   
256699          April-June     29/04/16     2016-04-29  2016  April      Q2   
256700          April-June     29/04/16     2016-04-29  2016  April      Q2   
256701          April-June     29/04/16 

In [53]:
# View frequency of dates in 'Survey_date_dt' column.
Rst_16_Q2['Survey_date_dt'].value_counts()

2016-06-22    64
2016-06-28    64
2016-04-28    64
2016-04-29    64
Name: Survey_date_dt, dtype: int64

In [54]:
# View frequency of sites in 'Site ID' column.
Rst_16_Q2['Site ID'].value_counts()

CENCY063    128
CENCY701    128
Name: Site ID, dtype: int64

In [55]:
# Check dates related to CENCY063 site ID in 2016 Q2.
Rst_16_Q2.loc[Rst_16_Q2['Site ID'] == 'CENCY063']['Survey_date_dt'].value_counts(sort=False)

2016-06-22    64
2016-06-28    64
Name: Survey_date_dt, dtype: int64

In [56]:
# View frequency of time slots in 'Time' column.
Rst_16_Q2['Time'].value_counts()

0600 - 0615    4
0615 - 0630    4
1430 - 1445    4
1445 - 1500    4
1500 - 1515    4
              ..
1230 - 1245    4
1245 - 1300    4
1300 - 1315    4
1315 - 1330    4
2145 - 2200    4
Name: Time, Length: 64, dtype: int64

In [57]:
# Select rows related to 2016 Q4.
Rst_16_Q4 = Rst.loc[Rst['Year-Quarter'] == '2016-Q4'].sort_index() 

# View DataFrame.
Rst_16_Q4

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
290368     2016 Q4 (October-December)                   2016-17 Q3  CENCY063   
290369     2016 Q4 (October-December)                   2016-17 Q3  CENCY063   
290370     2016 Q4 (October-December)                   2016-17 Q3  CENCY063   
290371     2016 Q4 (October-December)                   2016-17 Q3  CENCY063   
290372     2016 Q4 (October-December)                   2016-17 Q3  CENCY063   
...                               ...                          ...       ...   
308027     2016 Q4 (October-December)                   2016-17 Q3  CENCY701   
308028     2016 Q4 (October-December)                   2016-17 Q3  CENCY701   
308029     2016 Q4 (October-December)                   2016-17 Q3  CENCY701   
308030     2016 Q4 (October-December)                   2016-17 Q3  CENCY701   
308031     2016 Q4 (October-December)                   2016-17 Q3  CENCY701   

             Location    Survey date Weather         Time  \
290368  Regent Street  ven, 16/12/16     Dry  0600 - 0615   
290369  Regent Street  ven, 16/12/16     Dry  0615 - 0630   
290370  Regent Street  ven, 16/12/16     Dry  0630 - 0645   
290371  Regent Street  ven, 16/12/16     Dry  0645 - 0700   
290372  Regent Street  ven, 16/12/16     Dry  0700 - 0715   
...               ...            ...     ...          ...   
308027  Regent Street  jeu, 17/11/16     Dry  2045 - 2100   
308028  Regent Street  jeu, 17/11/16     Dry  2100 - 2115   
308029  Regent Street  jeu, 17/11/16     Dry  2115 - 2130   
308030  Regent Street  jeu, 17/11/16     Dry  2130 - 2145   
308031  Regent Street  jeu, 17/11/16     Dry  2145 - 2200   

                             Period   Direction  Start hour  ...  \
290368  Early Morning (06:00-07:00)  Northbound         6.0  ...   
290369  Early Morning (06:00-07:00)  Northbound         6.0  ...   
290370  Early Morning (06:00-07:00)  Northbound         6.0  ...   
290371  Early Morning (06:00-07:00)  Northbound         6.0  ...   
290372        AM peak (07:00-10:00)  Northbound         7.0  ...   
...                             ...         ...         ...  ...   
308027        Evening (19:00-22:00)  Southbound        20.0  ...   
308028        Evening (19:00-22:00)  Southbound        21.0  ...   
308029        Evening (19:00-22:00)  Southbound        21.0  ...   
308030        Evening (19:00-22:00)  Southbound        21.0  ...   
308031        Evening (19:00-22:00)  Southbound        21.0  ...   

        Total cycles  Survey_wave_year  Survey_wave_quater  \
290368           0.0              2016                  Q4   
290369           0.0              2016                  Q4   
290370           7.0              2016                  Q4   
290371          12.0              2016                  Q4   
290372           3.0              2016                  Q4   
...              ...               ...                 ...   
308027           0.0              2016                  Q4   
308028           0.0              2016                  Q4   
308029           1.0              2016                  Q4   
308030           0.0              2016                  Q4   
308031           0.0              2016                  Q4   

        Survey_wave_months  Survey_date Survey_date_dt  Year     Month  \
290368    October-December     16/12/16     2016-12-16  2016  December   
290369    October-December     16/12/16     2016-12-16  2016  December   
290370    October-December     16/12/16     2016-12-16  2016  December   
290371    October-December     16/12/16     2016-12-16  2016  December   
290372    October-December     16/12/16     2016-12-16  2016  December   
...                    ...          ...            ...   ...       ...   
308027    October-December     17/11/16     2016-11-17  2016  November   
308028    October-December     17/11/16     2016-11-17  2016  November   
308029    October-December     17/11/16     2016-11-17  2016  November   
308030    O

In [58]:
# View frequency of dates in 'Survey_date_dt' column.
Rst_16_Q4['Survey_date_dt'].value_counts(sort=False)

2016-12-16    74
2016-12-12    16
2016-12-15    38
2016-11-18    12
2016-11-22    24
2016-11-15    36
2016-11-16    10
2016-11-17    32
2016-11-21    14
Name: Survey_date_dt, dtype: int64

In [59]:
# See dates order.
a = Rst_16_Q4['Survey_date_dt'].drop_duplicates()
a

# No consistency of date order (by index), e.g. 2016-11-21 is in between of rows related to data for 2016-11-17. 
# BUT within Qs months are in descending order.

290368   2016-12-16
290381   2016-12-12
290389   2016-12-15
307904   2016-11-18
307910   2016-11-22
307922   2016-11-15
307930   2016-11-16
307935   2016-11-17
307944   2016-11-21
Name: Survey_date_dt, dtype: datetime64[ns]

In [60]:
# View frequency of sites in 'Site ID' column.
Rst_16_Q4['Site ID'].value_counts()

CENCY063    128
CENCY701    128
Name: Site ID, dtype: int64

In [61]:
# Check dates related to CENCY063 site ID in 2016 Q4.
Rst_16_Q4.loc[Rst_16_Q4['Site ID'] == 'CENCY063']['Survey_date_dt'].value_counts(sort=False)

2016-12-16    74
2016-12-12    16
2016-12-15    38
Name: Survey_date_dt, dtype: int64

In [62]:
# View frequency of time slots in 'Time' column.
Rst_16_Q4['Time'].value_counts()

0600 - 0615    4
0615 - 0630    4
1430 - 1445    4
1445 - 1500    4
1500 - 1515    4
              ..
1230 - 1245    4
1245 - 1300    4
1300 - 1315    4
1315 - 1330    4
2145 - 2200    4
Name: Time, Length: 64, dtype: int64

#### 2015

In [63]:
# Select rows from the main DataFrame with location 'Regent Street' and 'Year-Quarter' column == 2015 Q3.
Rst_15_Q3 = L_centr_fnl_0[(L_centr_fnl_0['Location'] == 'Regent Street') & 
                          (L_centr_fnl_0['Year-Quarter'] == '2015-Q3')].sort_index()

Rst_15_Q3

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
161984       2015 Q3 (July-September)                   2015-16 Q2  CENCY063   
161985       2015 Q3 (July-September)                   2015-16 Q2  CENCY063   
161986       2015 Q3 (July-September)                   2015-16 Q2  CENCY063   
161987       2015 Q3 (July-September)                   2015-16 Q2  CENCY063   
161988       2015 Q3 (July-September)                   2015-16 Q2  CENCY063   
...                               ...                          ...       ...   
179643       2015 Q3 (July-September)                   2015-16 Q2  CENCY701   
179644       2015 Q3 (July-September)                   2015-16 Q2  CENCY701   
179645       2015 Q3 (July-September)                   2015-16 Q2  CENCY701   
179646       2015 Q3 (July-September)                   2015-16 Q2  CENCY701   
179647       2015 Q3 (July-September)                   2015-16 Q2  CENCY701   

             Location    Survey date        Weather         Time  \
161984  Regent Street  lun, 14/09/15  Light Showers  0600 - 0615   
161985  Regent Street  lun, 14/09/15  Light Showers  0615 - 0630   
161986  Regent Street  lun, 14/09/15  Light Showers  0630 - 0645   
161987  Regent Street  lun, 14/09/15  Light Showers  0645 - 0700   
161988  Regent Street  lun, 14/09/15  Light Showers  0700 - 0715   
...               ...            ...            ...          ...   
179643  Regent Street  jeu, 30/07/15            Dry  2045 - 2100   
179644  Regent Street  jeu, 30/07/15            Dry  2100 - 2115   
179645  Regent Street  jeu, 30/07/15            Dry  2115 - 2130   
179646  Regent Street  jeu, 30/07/15            Dry  2130 - 2145   
179647  Regent Street  jeu, 30/07/15            Dry  2145 - 2200   

                             Period   Direction  Start hour  ...  \
161984  Early Morning (06:00-07:00)  Northbound         6.0  ...   
161985  Early Morning (06:00-07:00)  Northbound         6.0  ...   
161986  Early Morning (06:00-07:00)  Northbound         6.0  ...   
161987  Early Morning (06:00-07:00)  Northbound         6.0  ...   
161988        AM peak (07:00-10:00)  Northbound         7.0  ...   
...                             ...         ...         ...  ...   
179643        Evening (19:00-22:00)  Southbound        20.0  ...   
179644        Evening (19:00-22:00)  Southbound        21.0  ...   
179645        Evening (19:00-22:00)  Southbound        21.0  ...   
179646        Evening (19:00-22:00)  Southbound        21.0  ...   
179647        Evening (19:00-22:00)  Southbound        21.0  ...   

        Total cycles  Survey_wave_year  Survey_wave_quater  \
161984           0.0              2015                  Q3   
161985           4.0              2015                  Q3   
161986           4.0              2015                  Q3   
161987           2.0              2015                  Q3   
161988           6.0              2015                  Q3   
...              ...               ...                 ...   
179643           0.0              2015                  Q3   
179644           0.0              2015                  Q3   
179645           0.0              2015                  Q3   
179646           0.0              2015                  Q3   
179647           0.0              2015                  Q3   

        Survey_wave_months  Survey_date Survey_date_dt  Year      Month  \
161984      July-September     14/09/15     2015-09-14  2015  September   
161985      July-September     14/09/15     2015-09-14  2015  September   
161986      July-September     14/09/15     2015-09-14  2015  September   
161987      July-September     14/09/15     2015-09-14  2015  September   
161988      July-September     14/09/15     2015-09-14  2015  September   
...                    ...          ...            ...   ...        ...   
179643      July-September     30/07/15     2015-07-30  2015       July   
179644      July-September     30/07/15     2015-07-30  2015       

In [64]:
# View frequency of dates in 'Survey_date_dt' column.
Rst_15_Q3['Survey_date_dt'].value_counts(sort=False)

2015-09-14    56
2015-09-16    72
2015-07-30    52
2015-07-31    38
2015-08-03    38
Name: Survey_date_dt, dtype: int64

In [65]:
# See dates order.
b = Rst_15_Q3['Survey_date_dt'].drop_duplicates()
b

# No consistency of date order (by index), e.g. 2016-11-21 is in between of rows related to data for 2016-11-17. 
# BUT within Qs months are in descending order.

161984   2015-09-14
162012   2015-09-16
179520   2015-07-30
179536   2015-07-31
179548   2015-08-03
Name: Survey_date_dt, dtype: datetime64[ns]

In [66]:
# View frequency of sites in 'Site ID' column.
Rst_15_Q3['Site ID'].value_counts()

CENCY063    128
CENCY701    128
Name: Site ID, dtype: int64

In [67]:
# Check dates related to CENCY063 site ID in 2015 Q3.
Rst_15_Q3.loc[Rst_15_Q3['Site ID'] == 'CENCY063']['Survey_date_dt'].value_counts(sort=False)

2015-09-14    56
2015-09-16    72
Name: Survey_date_dt, dtype: int64

In [68]:
# Select rows from the main DataFrame with location 'Regent Street' and 'Year-Quarter' column == 2015 Q1.
Rst_15_Q1 = L_centr_fnl_0[(L_centr_fnl_0['Location'] == 'Regent Street') & 
                          (L_centr_fnl_0['Year-Quarter'] == '2015-Q1')].sort_index()

Rst_15_Q1

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
110528        2015 Q1 (January-March)                   2014-15 Q4  CENCY063   
110529        2015 Q1 (January-March)                   2014-15 Q4  CENCY063   
110530        2015 Q1 (January-March)                   2014-15 Q4  CENCY063   
110531        2015 Q1 (January-March)                   2014-15 Q4  CENCY063   
110532        2015 Q1 (January-March)                   2014-15 Q4  CENCY063   
...                               ...                          ...       ...   
128187        2015 Q1 (January-March)                   2014-15 Q4  CENCY701   
128188        2015 Q1 (January-March)                   2014-15 Q4  CENCY701   
128189        2015 Q1 (January-March)                   2014-15 Q4  CENCY701   
128190        2015 Q1 (January-March)                   2014-15 Q4  CENCY701   
128191        2015 Q1 (January-March)                   2014-15 Q4  CENCY701   

             Location    Survey date Weather         Time  \
110528  Regent Street  mer, 25/03/15    Fine  0600 - 0615   
110529  Regent Street  mer, 25/03/15    Fine  0615 - 0630   
110530  Regent Street  mer, 25/03/15    Fine  0630 - 0645   
110531  Regent Street  mer, 25/03/15    Fine  0645 - 0700   
110532  Regent Street  mer, 25/03/15    Fine  0700 - 0715   
...               ...            ...     ...          ...   
128187  Regent Street  mer, 11/02/15    Fine  2045 - 2100   
128188  Regent Street  mer, 11/02/15    Fine  2100 - 2115   
128189  Regent Street  mer, 11/02/15    Fine  2115 - 2130   
128190  Regent Street  mer, 11/02/15    Fine  2130 - 2145   
128191  Regent Street  mer, 11/02/15    Fine  2145 - 2200   

                             Period   Direction  Start hour  ...  \
110528  Early Morning (06:00-07:00)  Northbound         6.0  ...   
110529  Early Morning (06:00-07:00)  Northbound         6.0  ...   
110530  Early Morning (06:00-07:00)  Northbound         6.0  ...   
110531  Early Morning (06:00-07:00)  Northbound         6.0  ...   
110532        AM peak (07:00-10:00)  Northbound         7.0  ...   
...                             ...         ...         ...  ...   
128187        Evening (19:00-22:00)  Southbound        20.0  ...   
128188        Evening (19:00-22:00)  Southbound        21.0  ...   
128189        Evening (19:00-22:00)  Southbound        21.0  ...   
128190        Evening (19:00-22:00)  Southbound        21.0  ...   
128191        Evening (19:00-22:00)  Southbound        21.0  ...   

        Total cycles  Survey_wave_year  Survey_wave_quater  \
110528           5.0              2015                  Q1   
110529          20.0              2015                  Q1   
110530           7.0              2015                  Q1   
110531          14.0              2015                  Q1   
110532          12.0              2015                  Q1   
...              ...               ...                 ...   
128187           0.0              2015                  Q1   
128188           3.0              2015                  Q1   
128189           0.0              2015                  Q1   
128190           0.0              2015                  Q1   
128191           0.0              2015                  Q1   

        Survey_wave_months  Survey_date Survey_date_dt  Year     Month  \
110528       January-March     25/03/15     2015-03-25  2015     March   
110529       January-March     25/03/15     2015-03-25  2015     March   
110530       January-March     25/03/15     2015-03-25  2015     March   
110531       January-March     25/03/15     2015-03-25  2015     March   
110532       January-March     25/03/15     2015-03-25  2015     March   
...                    ...          ...            ...   ...       ...   
128187       January-March     11/02/15     2015-02-11  2015  February   
128188       January-March     11/02/15     2015-02-11  2015  February   
128189       January-March     11/02/15     2015-02-11  2015  February   
128190     

In [69]:
# View frequency of dates in 'Survey_date_dt' column.
Rst_15_Q1['Survey_date_dt'].value_counts(sort=False)

2015-03-25    64
2015-03-16    64
2015-02-10    64
2015-02-11    64
Name: Survey_date_dt, dtype: int64

In [70]:
# View frequency of sites in 'Site ID' column.
Rst_15_Q1['Site ID'].value_counts()

CENCY063    128
CENCY701    128
Name: Site ID, dtype: int64

In [71]:
# Check dates related to CENCY063 site ID in 2015 Q1.
Rst_15_Q1.loc[Rst_15_Q1['Site ID'] == 'CENCY063']['Survey_date_dt'].value_counts(sort=False)

2015-03-25    64
2015-03-16    64
Name: Survey_date_dt, dtype: int64

In [72]:
# Select rows from the main DataFrame with location 'Regent Street' and 'Year-Quarter' column == 2015 Q2.
Rst_15_Q2 = L_centr_fnl_0[(L_centr_fnl_0['Location'] == 'Regent Street') & 
                          (L_centr_fnl_0['Year-Quarter'] == '2015-Q2')].sort_index()

Rst_15_Q2

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
136256           2015 Q2 (April-June)                   2015-16 Q1  CENCY063   
136257           2015 Q2 (April-June)                   2015-16 Q1  CENCY063   
136258           2015 Q2 (April-June)                   2015-16 Q1  CENCY063   
136259           2015 Q2 (April-June)                   2015-16 Q1  CENCY063   
136260           2015 Q2 (April-June)                   2015-16 Q1  CENCY063   
...                               ...                          ...       ...   
153915           2015 Q2 (April-June)                   2015-16 Q1  CENCY701   
153916           2015 Q2 (April-June)                   2015-16 Q1  CENCY701   
153917           2015 Q2 (April-June)                   2015-16 Q1  CENCY701   
153918           2015 Q2 (April-June)                   2015-16 Q1  CENCY701   
153919           2015 Q2 (April-June)                   2015-16 Q1  CENCY701   

             Location    Survey date Weather         Time  \
136256  Regent Street  lun, 15/06/15    Fine  0600 - 0615   
136257  Regent Street  lun, 15/06/15    Fine  0615 - 0630   
136258  Regent Street  lun, 15/06/15    Fine  0630 - 0645   
136259  Regent Street  lun, 15/06/15    Fine  0645 - 0700   
136260  Regent Street  lun, 15/06/15    Fine  0700 - 0715   
...               ...            ...     ...          ...   
153915  Regent Street  ven, 15/05/15     Dry  2045 - 2100   
153916  Regent Street  ven, 15/05/15     Dry  2100 - 2115   
153917  Regent Street  ven, 15/05/15     Dry  2115 - 2130   
153918  Regent Street  ven, 15/05/15     Dry  2130 - 2145   
153919  Regent Street  ven, 15/05/15     Dry  2145 - 2200   

                             Period   Direction  Start hour  ...  \
136256  Early Morning (06:00-07:00)  Northbound         6.0  ...   
136257  Early Morning (06:00-07:00)  Northbound         6.0  ...   
136258  Early Morning (06:00-07:00)  Northbound         6.0  ...   
136259  Early Morning (06:00-07:00)  Northbound         6.0  ...   
136260        AM peak (07:00-10:00)  Northbound         7.0  ...   
...                             ...         ...         ...  ...   
153915        Evening (19:00-22:00)  Southbound        20.0  ...   
153916        Evening (19:00-22:00)  Southbound        21.0  ...   
153917        Evening (19:00-22:00)  Southbound        21.0  ...   
153918        Evening (19:00-22:00)  Southbound        21.0  ...   
153919        Evening (19:00-22:00)  Southbound        21.0  ...   

        Total cycles  Survey_wave_year  Survey_wave_quater  \
136256           0.0              2015                  Q2   
136257           4.0              2015                  Q2   
136258           5.0              2015                  Q2   
136259           7.0              2015                  Q2   
136260           9.0              2015                  Q2   
...              ...               ...                 ...   
153915           0.0              2015                  Q2   
153916           0.0              2015                  Q2   
153917           0.0              2015                  Q2   
153918           0.0              2015                  Q2   
153919           0.0              2015                  Q2   

        Survey_wave_months  Survey_date Survey_date_dt  Year Month Quarter  \
136256          April-June     15/06/15     2015-06-15  2015  June      Q2   
136257          April-June     15/06/15     2015-06-15  2015  June      Q2   
136258          April-June     15/06/15     2015-06-15  2015  June      Q2   
136259          April-June     15/06/15     2015-06-15  2015  June      Q2   
136260          April-June     15/06/15     2015-06-15  2015  June      Q2   
...                    ...          ...            ...   ...   ...     ...   
153915          April-June     15/05/15     2015-05-15  2015   May      Q2   
153916          April-June     15/05/15     2015-05-15  2015   May      Q2   
153917          April-June     15/05/15     2015-

In [73]:
# View frequency of dates in 'Survey_date_dt' column.
Rst_15_Q2['Survey_date_dt'].value_counts(sort=False)

2015-06-15    56
2015-06-24    72
2015-05-14    64
2015-05-15    64
Name: Survey_date_dt, dtype: int64

In [74]:
# View frequency of sites in 'Site ID' column.
Rst_15_Q2['Site ID'].value_counts()

CENCY063    128
CENCY701    128
Name: Site ID, dtype: int64

In [75]:
# Check dates related to CENCY063 site ID in 2015 Q2.
Rst_15_Q2.loc[Rst_15_Q2['Site ID'] == 'CENCY063']['Survey_date_dt'].value_counts(sort=False)

2015-06-15    56
2015-06-24    72
Name: Survey_date_dt, dtype: int64

In [76]:
# Select rows from the main DataFrame with location 'Regent Street' and 'Year-Quarter' column == 2015 Q4.
Rst_15_Q4 = L_centr_fnl_0[(L_centr_fnl_0['Location'] == 'Regent Street') & 
                          (L_centr_fnl_0['Year-Quarter'] == '2015-Q4')].sort_index()

Rst_15_Q4

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
187712     2015 Q4 (October-December)                   2015-16 Q3  CENCY063   
187713     2015 Q4 (October-December)                   2015-16 Q3  CENCY063   
187714     2015 Q4 (October-December)                   2015-16 Q3  CENCY063   
187715     2015 Q4 (October-December)                   2015-16 Q3  CENCY063   
187716     2015 Q4 (October-December)                   2015-16 Q3  CENCY063   
...                               ...                          ...       ...   
205371     2015 Q4 (October-December)                   2015-16 Q3  CENCY701   
205372     2015 Q4 (October-December)                   2015-16 Q3  CENCY701   
205373     2015 Q4 (October-December)                   2015-16 Q3  CENCY701   
205374     2015 Q4 (October-December)                   2015-16 Q3  CENCY701   
205375     2015 Q4 (October-December)                   2015-16 Q3  CENCY701   

             Location    Survey date Weather         Time  \
187712  Regent Street  jeu, 03/12/15     Dry  0600 - 0615   
187713  Regent Street  jeu, 03/12/15     Dry  0615 - 0630   
187714  Regent Street  jeu, 03/12/15     Dry  0630 - 0645   
187715  Regent Street  jeu, 03/12/15     Dry  0645 - 0700   
187716  Regent Street  jeu, 03/12/15     Dry  0700 - 0715   
...               ...            ...     ...          ...   
205371  Regent Street  mar, 03/11/15    Fine  2045 - 2100   
205372  Regent Street  mar, 03/11/15    Fine  2100 - 2115   
205373  Regent Street  mar, 03/11/15    Fine  2115 - 2130   
205374  Regent Street  mar, 03/11/15    Fine  2130 - 2145   
205375  Regent Street  mar, 03/11/15    Fine  2145 - 2200   

                             Period   Direction  Start hour  ...  \
187712  Early Morning (06:00-07:00)  Northbound         6.0  ...   
187713  Early Morning (06:00-07:00)  Northbound         6.0  ...   
187714  Early Morning (06:00-07:00)  Northbound         6.0  ...   
187715  Early Morning (06:00-07:00)  Northbound         6.0  ...   
187716        AM peak (07:00-10:00)  Northbound         7.0  ...   
...                             ...         ...         ...  ...   
205371        Evening (19:00-22:00)  Southbound        20.0  ...   
205372        Evening (19:00-22:00)  Southbound        21.0  ...   
205373        Evening (19:00-22:00)  Southbound        21.0  ...   
205374        Evening (19:00-22:00)  Southbound        21.0  ...   
205375        Evening (19:00-22:00)  Southbound        21.0  ...   

        Total cycles  Survey_wave_year  Survey_wave_quater  \
187712           0.0              2015                  Q4   
187713          15.0              2015                  Q4   
187714           9.0              2015                  Q4   
187715           9.0              2015                  Q4   
187716           1.0              2015                  Q4   
...              ...               ...                 ...   
205371           1.0              2015                  Q4   
205372           0.0              2015                  Q4   
205373           0.0              2015                  Q4   
205374           0.0              2015                  Q4   
205375           0.0              2015                  Q4   

        Survey_wave_months  Survey_date Survey_date_dt  Year     Month  \
187712    October-December     03/12/15     2015-12-03  2015  December   
187713    October-December     03/12/15     2015-12-03  2015  December   
187714    October-December     03/12/15     2015-12-03  2015  December   
187715    October-December     03/12/15     2015-12-03  2015  December   
187716    October-December     03/12/15     2015-12-03  2015  December   
...                    ...          ...            ...   ...       ...   
205371    October-December     03/11/15     2015-11-03  2015  November   
205372    October-December     03/11/15     2015-11-03  2015  November   
205373    October-December     03/11/15     2015-11-03  2015  November   
205374    O

In [77]:
# View frequency of dates in 'Survey_date_dt' column.
Rst_15_Q4['Survey_date_dt'].value_counts(sort=False)

2015-12-03    64
2015-12-04    64
2015-11-05    32
2015-11-03    64
2015-11-02    32
Name: Survey_date_dt, dtype: int64

In [78]:
# View frequency of sites in 'Site ID' column.
Rst_15_Q4['Site ID'].value_counts()

CENCY063    128
CENCY701    128
Name: Site ID, dtype: int64

In [79]:
# Check dates related to CENCY063 site ID in 2015 Q4.
Rst_15_Q4.loc[Rst_15_Q4['Site ID'] == 'CENCY063']['Survey_date_dt'].value_counts(sort=False)

2015-12-03    64
2015-12-04    64
Name: Survey_date_dt, dtype: int64

**OBSERVATIONS AND INSIGHTS:**

7424 observations
128 NaN - all related to 2016 Q3 (July-September)
256 observations per Q
2 sites/locations: CENCY063 and CENCY701
128 entries per site ID in each Q
64 time slots per day from 6am to 10 pm (every 15 mins) **SOMETIMES SPLIT BETWEEN DATES**
All missing values are related to CENCY701 site ID (128 entries)

No consistency of date order (by index), e.g. 2016-11-21 is in between of rows related to data for 2016-11-17. 
BUT months within each Q are **ALMOST** all in the descending order. 
Observations from different site IDs were recorded in different months => CENCY063 - always last month of Q;
CENCY701 – 1st or/and 2nd month of Q.

**Therefore the decision was made to keep the missing dates (1.37% of all entries) as NaT**

In [80]:
# Drop 'Survey_date' column.
L_centr_fnl_0 = L_centr_fnl_0.drop(columns=['Survey_date']).reset_index(drop=True)

In [81]:
# Rename 'Survey_date_dt' column into 'Date'.
L_centr_fnl_0 = L_centr_fnl_0.rename(columns={'Survey_date_dt':'Date'})

# View DataFrame.
L_centr_fnl_0.head()

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
0        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
1        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
2        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
3        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
4        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   

                             Location    Survey date Weather         Time  \
0  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0600 - 0615   
1  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0615 - 0630   
2  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0630 - 0645   
3  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0645 - 0700   
4  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0700 - 0715   

                        Period   Direction  Start hour  ...  \
0  Early Morning (06:00-07:00)  Northbound         6.0  ...   
1  Early Morning (06:00-07:00)  Northbound         6.0  ...   
2  Early Morning (06:00-07:00)  Northbound         6.0  ...   
3  Early Morning (06:00-07:00)  Northbound         6.0  ...   
4        AM peak (07:00-10:00)  Northbound         7.0  ...   

   Number of cycle hire bikes  Total cycles  Survey_wave_year  \
0                         0.0           0.0              2014   
1                         0.0          15.0              2014   
2                         0.0          35.0              2014   
3                         2.0          61.0              2014   
4                         0.0          73.0              2014   

   Survey_wave_quater  Survey_wave_months       Date  Year    Month  Quarter  \
0                  Q1       January-March 2014-01-24  2014  January       Q1   
1                  Q1       January-March 2014-01-24  2014  January       Q1   
2                  Q1       January-March 2014-01-24  2014  January       Q1   
3                  Q1       January-March 2014-01-24  2014  January       Q1   
4                  Q1       January-March 2014-01-24  2014  January       Q1   

  Year-Quarter  
0      2014-Q1  
1      2014-Q1  
2      2014-Q1  
3      2014-Q1  
4      2014-Q1  

[5 rows x 22 columns]

In [82]:
# Add a column with days of the week.
L_centr_fnl_0['Day'] = L_centr_fnl_0['Date'].dt.day_name()

# View DataFrame.
L_centr_fnl_0.head()

Survey wave (calendar quarter) Equivalent financial quarter   Site ID  \
0        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
1        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
2        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
3        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   
4        2014 Q1 (January-March)                   2013-14 Q4  CENCY001   

                             Location    Survey date Weather         Time  \
0  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0600 - 0615   
1  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0615 - 0630   
2  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0630 - 0645   
3  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0645 - 0700   
4  Millbank (south of Thorney Street)  ven, 24/01/14     Dry  0700 - 0715   

                        Period   Direction  Start hour  ...  Total cycles  \
0  Early Morning (06:00-07:00)  Northbound         6.0  ...           0.0   
1  Early Morning (06:00-07:00)  Northbound         6.0  ...          15.0   
2  Early Morning (06:00-07:00)  Northbound         6.0  ...          35.0   
3  Early Morning (06:00-07:00)  Northbound         6.0  ...          61.0   
4        AM peak (07:00-10:00)  Northbound         7.0  ...          73.0   

   Survey_wave_year  Survey_wave_quater  Survey_wave_months       Date  Year  \
0              2014                  Q1       January-March 2014-01-24  2014   
1              2014                  Q1       January-March 2014-01-24  2014   
2              2014                  Q1       January-March 2014-01-24  2014   
3              2014                  Q1       January-March 2014-01-24  2014   
4              2014                  Q1       January-March 2014-01-24  2014   

     Month Quarter  Year-Quarter     Day  
0  January      Q1       2014-Q1  Friday  
1  January      Q1       2014-Q1  Friday  
2  January      Q1       2014-Q1  Friday  
3  January      Q1       2014-Q1  Friday  
4  January      Q1       2014-Q1  Friday  

[5 rows x 23 columns]

# OUTER LONDON DATA SET

In [83]:
# Read the provided CSV file/data set.
london_outer = pd.read_csv('Outer London.csv') 

# Print the output.
print(london_outer.info())
london_outer.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375660 entries, 0 to 375659
Data columns (total 14 columns):
 #   Column                    Non-Null Count   Dtype 
---  ------                    --------------   ----- 
 0   Survey wave (year)        375660 non-null  int64 
 1   Site ID                   375660 non-null  object
 2   Location                  375660 non-null  object
 3   Survey date               374492 non-null  object
 4   Weather                   374692 non-null  object
 5   Time                      375660 non-null  object
 6   Period                    375660 non-null  object
 7   Direction                 375660 non-null  object
 8   Start hour                375660 non-null  int64 
 9   Start minute              375660 non-null  int64 
 10  Number of male cycles     375660 non-null  int64 
 11  Number of female cycles   375660 non-null  int64 
 12  Number of unknown cycles  375660 non-null  int64 
 13  Total cycles              375660 non-null  int64 
dtypes: i

Survey wave (year)   Site ID                      Location  \
375655                2021  OUTCY451  Thames Path (Lower Ham Road)   
375656                2021  OUTCY451  Thames Path (Lower Ham Road)   
375657                2021  OUTCY451  Thames Path (Lower Ham Road)   
375658                2021  OUTCY451  Thames Path (Lower Ham Road)   
375659                2021  OUTCY451  Thames Path (Lower Ham Road)   

          Survey date Weather         Time                 Period   Direction  \
375655  ven, 18/06/21     Wet  2045 - 2100  Evening (19:00-22:00)  Southbound   
375656  ven, 18/06/21     Wet  2100 - 2115  Evening (19:00-22:00)  Southbound   
375657  ven, 18/06/21     Wet  2115 - 2130  Evening (19:00-22:00)  Southbound   
375658  ven, 18/06/21     Wet  2130 - 2145  Evening (19:00-22:00)  Southbound   
375659  ven, 18/06/21     Wet  2145 - 2200  Evening (19:00-22:00)  Southbound   

        Start hour  Start minute  Number of male cycles  \
375655          20            45                      1   
375656          21             0                      2   
375657          21            15                      0   
375658          21            30                      0   
375659          21            45                      1   

        Number of female cycles  Number of unknown cycles  Total cycles  
375655                        0                         0             1  
375656                        0                         0             2  
375657                        0                         0             0  
375658                        0                         0             0  
375659                        0                         0             1

## Cleaning Date and Time related Columns

In [84]:
# Check dataframe info
london_outer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375660 entries, 0 to 375659
Data columns (total 14 columns):
 #   Column                    Non-Null Count   Dtype 
---  ------                    --------------   ----- 
 0   Survey wave (year)        375660 non-null  int64 
 1   Site ID                   375660 non-null  object
 2   Location                  375660 non-null  object
 3   Survey date               374492 non-null  object
 4   Weather                   374692 non-null  object
 5   Time                      375660 non-null  object
 6   Period                    375660 non-null  object
 7   Direction                 375660 non-null  object
 8   Start hour                375660 non-null  int64 
 9   Start minute              375660 non-null  int64 
 10  Number of male cycles     375660 non-null  int64 
 11  Number of female cycles   375660 non-null  int64 
 12  Number of unknown cycles  375660 non-null  int64 
 13  Total cycles              375660 non-null  int64 
dtypes: i

In [85]:
# Split 'Survey date' column into two new columns.
london_outer[['Survey_week_day', 'Survey_date']] = london_outer['Survey date'].\
apply(lambda x: pd.Series(str(x).split(',')))

# View DataFrame.
london_outer.head()

Survey wave (year)   Site ID          Location    Survey date Weather  \
0                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   
1                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   
2                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   
3                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   
4                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   

          Time                       Period   Direction  Start hour  \
0  0600 - 0615  Early Morning (06:00-07:00)  Northbound           6   
1  0615 - 0630  Early Morning (06:00-07:00)  Northbound           6   
2  0630 - 0645  Early Morning (06:00-07:00)  Northbound           6   
3  0645 - 0700  Early Morning (06:00-07:00)  Northbound           6   
4  0700 - 0715        AM peak (07:00-10:00)  Northbound           7   

   Start minute  Number of male cycles  Number of female cycles  \
0             0                      2                        1   
1            15                      3                        0   
2            30                      2                        0   
3            45                      4                        0   
4             0                      4                        1   

   Number of unknown cycles  Total cycles Survey_week_day Survey_date  
0                         0             3             ven    26/06/15  
1                         0             3             ven    26/06/15  
2                         0             2             ven    26/06/15  
3                         0             4             ven    26/06/15  
4                         0             5             ven    26/06/15

In [86]:
# Drop 'Survey_week_day' column.
london_outer = london_outer.drop(columns='Survey_week_day').reset_index(drop=True)

In [87]:
# Remove whitespaces in 'Survey_date' column.
london_outer['Survey_date'] = london_outer['Survey_date'].str.replace(' ', '')

In [88]:
# Convert 'Survey_date' column to datetime dtype.
london_outer['Survey_date_dt'] = pd.to_datetime(london_outer['Survey_date'], format = '%d/%m/%y')

# View DataFrame.
london_outer.head()

Survey wave (year)   Site ID          Location    Survey date Weather  \
0                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   
1                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   
2                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   
3                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   
4                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   

          Time                       Period   Direction  Start hour  \
0  0600 - 0615  Early Morning (06:00-07:00)  Northbound           6   
1  0615 - 0630  Early Morning (06:00-07:00)  Northbound           6   
2  0630 - 0645  Early Morning (06:00-07:00)  Northbound           6   
3  0645 - 0700  Early Morning (06:00-07:00)  Northbound           6   
4  0700 - 0715        AM peak (07:00-10:00)  Northbound           7   

   Start minute  Number of male cycles  Number of female cycles  \
0             0                      2                        1   
1            15                      3                        0   
2            30                      2                        0   
3            45                      4                        0   
4             0                      4                        1   

   Number of unknown cycles  Total cycles Survey_date Survey_date_dt  
0                         0             3    26/06/15     2015-06-26  
1                         0             3    26/06/15     2015-06-26  
2                         0             2    26/06/15     2015-06-26  
3                         0             4    26/06/15     2015-06-26  
4                         0             5    26/06/15     2015-06-26

In [89]:
# Drop 'Survey_date' column.
london_outer = london_outer.drop(columns=['Survey_date']).reset_index(drop=True)

In [90]:
# Rename 'Survey_date_dt' column into 'Date'.
london_outer = london_outer.rename(columns={'Survey_date_dt':'Date'})

# View DataFrame.
london_outer.head()

Survey wave (year)   Site ID          Location    Survey date Weather  \
0                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   
1                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   
2                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   
3                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   
4                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   

          Time                       Period   Direction  Start hour  \
0  0600 - 0615  Early Morning (06:00-07:00)  Northbound           6   
1  0615 - 0630  Early Morning (06:00-07:00)  Northbound           6   
2  0630 - 0645  Early Morning (06:00-07:00)  Northbound           6   
3  0645 - 0700  Early Morning (06:00-07:00)  Northbound           6   
4  0700 - 0715        AM peak (07:00-10:00)  Northbound           7   

   Start minute  Number of male cycles  Number of female cycles  \
0             0                      2                        1   
1            15                      3                        0   
2            30                      2                        0   
3            45                      4                        0   
4             0                      4                        1   

   Number of unknown cycles  Total cycles       Date  
0                         0             3 2015-06-26  
1                         0             3 2015-06-26  
2                         0             2 2015-06-26  
3                         0             4 2015-06-26  
4                         0             5 2015-06-26

In [91]:
# Add a column with days of the week.
london_outer['Day'] = london_outer['Date'].dt.day_name()

# View DataFrame.
london_outer.head()

Survey wave (year)   Site ID          Location    Survey date Weather  \
0                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   
1                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   
2                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   
3                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   
4                2015  OUTCY001  High Road Leyton  ven, 26/06/15     Dry   

          Time                       Period   Direction  Start hour  \
0  0600 - 0615  Early Morning (06:00-07:00)  Northbound           6   
1  0615 - 0630  Early Morning (06:00-07:00)  Northbound           6   
2  0630 - 0645  Early Morning (06:00-07:00)  Northbound           6   
3  0645 - 0700  Early Morning (06:00-07:00)  Northbound           6   
4  0700 - 0715        AM peak (07:00-10:00)  Northbound           7   

   Start minute  Number of male cycles  Number of female cycles  \
0             0                      2                        1   
1            15                      3                        0   
2            30                      2                        0   
3            45                      4                        0   
4             0                      4                        1   

   Number of unknown cycles  Total cycles       Date     Day  
0                         0             3 2015-06-26  Friday  
1                         0             3 2015-06-26  Friday  
2                         0             2 2015-06-26  Friday  
3                         0             4 2015-06-26  Friday  
4                         0             5 2015-06-26  Friday

In [92]:
# Extract year from Date column.
london_outer['Year'] = london_outer['Date'].dt.strftime('%Y')

# Replace NaN values to 0 and convert values in the column to integer.
london_outer['Year'] = london_outer['Year'].fillna(0)
london_outer['Year'] = london_outer['Year'].astype(int)

# Compare extracted year to Survey_wave_year column.
london_outer[(london_outer['Survey wave (year)'] !=  london_outer['Year']) & (london_outer['Year'] > 0)]

# All dates in Date columns belong to the correct year.

Empty DataFrame
Columns: [Survey wave (year), Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of male cycles, Number of female cycles, Number of unknown cycles, Total cycles, Date, Day, Year]
Index: []

In [93]:
# Drop Year column.
london_outer = london_outer.drop(columns='Year').reset_index(drop=True)

In [94]:
# Extract year from Date column.
london_outer['Month'] = london_outer['Date'].dt.strftime('%B')

In [95]:
# Create a new column 'Quarter' and assign months from Month columns to the relevant calendar quarters.
london_outer['Quarter'] = ''

london_outer.loc[(london_outer['Month'] ==  'January') | 
                  (london_outer['Month'] ==  'February') |
                  (london_outer['Month'] ==  'March'), 
                  'Quarter'] = 'Q1'

london_outer.loc[(london_outer['Month'] ==  'April') | 
                  (london_outer['Month'] ==  'May') |
                  (london_outer['Month'] ==  'June'), 
                  'Quarter'] = 'Q2'

london_outer.loc[(london_outer['Month'] ==  'July') | 
                  (london_outer['Month'] ==  'August') |
                  (london_outer['Month'] ==  'September'), 
                  'Quarter'] = 'Q3'

london_outer.loc[(london_outer['Month'] ==  'October') | 
                  (london_outer['Month'] ==  'November') |
                  (london_outer['Month'] ==  'December'), 
                  'Quarter'] = 'Q4'

# Convert empty cells into NaN values and replace with 'Unknown'.
london_outer['Quarter'] = london_outer['Quarter'].replace('', np.nan, regex = True)
london_outer['Quarter'] = london_outer['Quarter'].fillna('Unknown')

In [96]:
# Check if Time periods are in line with Period column for Early Morning (06:00-07:00).
EM = london_outer[london_outer['Period'] == 'Early Morning (06:00-07:00)']

EM[(EM['Time'] != '0600 - 0615') & (EM['Time'] != '0615 - 0630') & (EM['Time'] != '0630 - 0645') &
  (EM['Time'] != '0645 - 0700')]

Empty DataFrame
Columns: [Survey wave (year), Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of male cycles, Number of female cycles, Number of unknown cycles, Total cycles, Date, Day, Month, Quarter]
Index: []

In [97]:
# Check if Time periods are in line with Period column for AM peak (07:00-10:00).
AP = london_outer[london_outer['Period'] == 'AM peak (07:00-10:00)']

AP[(AP['Time'] != '0700 - 0715') & (AP['Time'] != '0715 - 0730') & (AP['Time'] != '0730 - 0745') &
  (AP['Time'] != '0745 - 0800') & (AP['Time'] != '0800 - 0815') & (AP['Time'] != '0815 - 0830') & 
   (AP['Time'] != '0830 - 0845') & (AP['Time'] != '0845 - 0900') & (AP['Time'] != '0900 - 0915') & 
   (AP['Time'] != '0915 - 0930') & (AP['Time'] != '0930 - 0945') & (AP['Time'] != '0945 - 1000')]

Empty DataFrame
Columns: [Survey wave (year), Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of male cycles, Number of female cycles, Number of unknown cycles, Total cycles, Date, Day, Month, Quarter]
Index: []

In [98]:
# Check if Time periods are in line with Period column for Inter-peak (10:00-16:00).
IP = london_outer[london_outer['Period'] == 'Inter-peak (10:00-16:00)']

IP[(IP['Time'] != '1000 - 1015') & (IP['Time'] != '1015 - 1030') & (IP['Time'] != '1030 - 1045') &
  (IP['Time'] != '1045 - 1100') & (IP['Time'] != '1100 - 1115') & (IP['Time'] != '1115 - 1130') & 
   (IP['Time'] != '1130 - 1145') & (IP['Time'] != '1145 - 1200') & (IP['Time'] != '1200 - 1215') & 
   (IP['Time'] != '1215 - 1230') & (IP['Time'] != '1230 - 1245') & (IP['Time'] != '1245 - 1300') &
  (IP['Time'] != '1300 - 1315') & (IP['Time'] != '1315 - 1330') & (IP['Time'] != '1330 - 1345') &
  (IP['Time'] != '1345 - 1400') & (IP['Time'] != '1400 - 1415') & (IP['Time'] != '1415 - 1430') & 
   (IP['Time'] != '1430 - 1445') & (IP['Time'] != '1445 - 1500') & (IP['Time'] != '1500 - 1515') & 
   (IP['Time'] != '1515 - 1530') & (IP['Time'] != '1530 - 1545') & (IP['Time'] != '1545 - 1600')]

Empty DataFrame
Columns: [Survey wave (year), Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of male cycles, Number of female cycles, Number of unknown cycles, Total cycles, Date, Day, Month, Quarter]
Index: []

In [99]:
# Check if Time periods are in line with Period column for PM peak (16:00-19:00).
PP = london_outer[london_outer['Period'] == 'PM peak (16:00-19:00)']

PP[(PP['Time'] != '1600 - 1615') & (PP['Time'] != '1615 - 1630') & (PP['Time'] != '1630 - 1645') &
  (PP['Time'] != '1645 - 1700') & (PP['Time'] != '1700 - 1715') & (PP['Time'] != '1715 - 1730') & 
   (PP['Time'] != '1730 - 1745') & (PP['Time'] != '1745 - 1800') & (PP['Time'] != '1800 - 1815') & 
   (PP['Time'] != '1815 - 1830') & (PP['Time'] != '1830 - 1845') & (PP['Time'] != '1845 - 1900')]

Empty DataFrame
Columns: [Survey wave (year), Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of male cycles, Number of female cycles, Number of unknown cycles, Total cycles, Date, Day, Month, Quarter]
Index: []

In [100]:
# Check if Time periods are in line with Period column for Evening (19:00-22:00).
E = london_outer[london_outer['Period'] == 'Evening (19:00-22:00)']

E[(E['Time'] != '1900 - 1915') & (E['Time'] != '1915 - 1930') & (E['Time'] != '1930 - 1945') &
  (E['Time'] != '1945 - 2000') & (E['Time'] != '2000 - 2015') & (E['Time'] != '2015 - 2030') & 
   (E['Time'] != '2030 - 2045') & (E['Time'] != '2045 - 2100') & (E['Time'] != '2100 - 2115') & 
   (E['Time'] != '2115 - 2130') & (E['Time'] != '2130 - 2145') & (E['Time'] != '2145 - 2200')]

Empty DataFrame
Columns: [Survey wave (year), Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of male cycles, Number of female cycles, Number of unknown cycles, Total cycles, Date, Day, Month, Quarter]
Index: []

In [101]:
# View missing values.
london_outer.isnull().sum()

Survey wave (year)             0
Site ID                        0
Location                       0
Survey date                 1168
Weather                      968
Time                           0
Period                         0
Direction                      0
Start hour                     0
Start minute                   0
Number of male cycles          0
Number of female cycles        0
Number of unknown cycles       0
Total cycles                   0
Date                        1168
Day                         1168
Month                       1168
Quarter                        0
dtype: int64

### Missing values in Date related columns

In [102]:
# Select rows containing missing values in 'Date' column.
london_outer_1 = london_outer[london_outer['Date'].isnull()]

# View DataFrame.
london_outer_1.head()

Survey wave (year)   Site ID     Location Survey date Weather  \
3328                2015  OUTCY027  Morden Road         NaN     NaN   
3329                2015  OUTCY027  Morden Road         NaN     NaN   
3330                2015  OUTCY027  Morden Road         NaN     NaN   
3331                2015  OUTCY027  Morden Road         NaN     NaN   
3332                2015  OUTCY027  Morden Road         NaN     NaN   

             Time                       Period   Direction  Start hour  \
3328  0600 - 0615  Early Morning (06:00-07:00)  Northbound           6   
3329  0615 - 0630  Early Morning (06:00-07:00)  Northbound           6   
3330  0630 - 0645  Early Morning (06:00-07:00)  Northbound           6   
3331  0645 - 0700  Early Morning (06:00-07:00)  Northbound           6   
3332  0700 - 0715        AM peak (07:00-10:00)  Northbound           7   

      Start minute  Number of male cycles  Number of female cycles  \
3328             0                     10                        0   
3329            15                      9                        0   
3330            30                     21                        3   
3331            45                     29                        3   
3332             0                     21                        4   

      Number of unknown cycles  Total cycles Date  Day Month  Quarter  
3328                         0            10  NaT  NaN   NaN  Unknown  
3329                         0             9  NaT  NaN   NaN  Unknown  
3330                         0            24  NaT  NaN   NaN  Unknown  
3331                         0            32  NaT  NaN   NaN  Unknown  
3332                         0            25  NaT  NaN   NaN  Unknown

In [103]:
# View number of missing rows related to dates by year.
london_outer_1['Survey wave (year)'].value_counts().sort_index()

2015    384
2016    384
2017    384
2019     16
Name: Survey wave (year), dtype: int64

In [104]:
# View number of entries by year.
london_outer['Survey wave (year)'].value_counts().sort_index()

2015    57728
2016    57728
2017    57728
2018    57728
2019    57600
2020    29676
2021    57472
Name: Survey wave (year), dtype: int64

In [105]:
# Number of missing rows related to dates by Site ID.
london_outer_1['Site ID'].value_counts().sort_index()

OUTCY015    128
OUTCY027    128
OUTCY052    128
OUTCY163    128
OUTCY391    128
OUTCY393    128
OUTCY395     10
OUTCY400    256
OUTCY402    128
OUTCY408      6
Name: Site ID, dtype: int64

In [106]:
# Find first and last date in 'Date' column.
print(london_outer['Date'].min())
print(london_outer['Date'].max())

# View frequency of dates.
london_outer['Date'].value_counts()

2015-04-13 00:00:00
2021-07-24 00:00:00


2021-05-11    3252
2021-05-12    2896
2018-06-07    2716
2018-06-06    2688
2018-06-05    2560
              ... 
2017-06-08      18
2021-05-16      18
2019-05-29      16
2019-05-30      10
2017-07-09       2
Name: Date, Length: 435, dtype: int64

In [107]:
# Check dates in the order.
london_outer['Date'].value_counts().sort_index()

2015-04-13     176
2015-04-14     428
2015-04-15    1044
2015-04-16    1168
2015-04-17     650
              ... 
2021-07-16      64
2021-07-19      64
2021-07-22      62
2021-07-23      36
2021-07-24      34
Name: Date, Length: 435, dtype: int64

#### 2015

In [108]:
# View number of entries by month in 2015.
london_outer_2015 = london_outer[london_outer['Survey wave (year)'] == 2015]

london_outer_2015['Month'].value_counts()

June     23832
May      16446
April    10370
July      6696
Name: Month, dtype: int64

In [109]:
# Check where NaN values locate vs July month.
london_outer_2015_0J = london_outer_2015[(london_outer_2015['Month'] == 'July') | london_outer_2015['Month'].isnull()]

london_outer_2015_0J

Survey wave (year)   Site ID            Location    Survey date  \
32                   2015  OUTCY001    High Road Leyton  lun, 20/07/15   
33                   2015  OUTCY001    High Road Leyton  lun, 20/07/15   
34                   2015  OUTCY001    High Road Leyton  lun, 20/07/15   
35                   2015  OUTCY001    High Road Leyton  lun, 20/07/15   
36                   2015  OUTCY001    High Road Leyton  lun, 20/07/15   
...                   ...       ...                 ...            ...   
54011                2015  OUTCY422  Duke Humphrey Road  ven, 03/07/15   
54012                2015  OUTCY422  Duke Humphrey Road  ven, 03/07/15   
54013                2015  OUTCY422  Duke Humphrey Road  ven, 03/07/15   
54014                2015  OUTCY422  Duke Humphrey Road  ven, 03/07/15   
54015                2015  OUTCY422  Duke Humphrey Road  ven, 03/07/15   

      Weather         Time                    Period   Direction  Start hour  \
32        Dry  1400 - 1415  Inter-peak (10:00-16:00)  Northbound          14   
33        Dry  1415 - 1430  Inter-peak (10:00-16:00)  Northbound          14   
34        Dry  1430 - 1445  Inter-peak (10:00-16:00)  Northbound          14   
35        Dry  1445 - 1500  Inter-peak (10:00-16:00)  Northbound          14   
36        Dry  1500 - 1515  Inter-peak (10:00-16:00)  Northbound          15   
...       ...          ...                       ...         ...         ...   
54011     Dry  2045 - 2100     Evening (19:00-22:00)  Southbound          20   
54012     Dry  2100 - 2115     Evening (19:00-22:00)  Southbound          21   
54013     Dry  2115 - 2130     Evening (19:00-22:00)  Southbound          21   
54014     Dry  2130 - 2145     Evening (19:00-22:00)  Southbound          21   
54015     Dry  2145 - 2200     Evening (19:00-22:00)  Southbound          21   

       Start minute  Number of male cycles  Number of female cycles  \
32                0                      4                        0   
33               15                      0                        0   
34               30                      5                        0   
35               45                      3                        0   
36                0                      2                        0   
...             ...                    ...                      ...   
54011            45                      5                        1   
54012             0                      0                        0   
54013            15                      2                        0   
54014            30                      0                        0   
54015            45                      0                        0   

       Number of unknown cycles  Total cycles       Date     Day Month Quarter  
32                            0             4 2015-07-20  Monday  July      Q3  
33                            0             0 2015-07-20  Monday  July      Q3  
34                            0             5 2015-07-20  Monday  July      Q3  
35                            0             3 2015-07-20  Monday  July      Q3  
36                            0             2 2015-07-20  Monday  July      Q3  
...                         ...           ...        ...     ...   ...     ...  
54011                         0             6 2015-07-03  Friday  July      Q3  
54012                         0             0 2015-07-03  Friday  July      Q3  
54013                         0             2 2015-07-03  Friday  July      Q3  
54014                         0             0 2015-07-03  Friday  July      Q3  
54015                         0             0 2015-07-03  Friday  July      Q3  

[7080 rows x 18 columns]

In [110]:
# Number of entries by Site ID.
london_outer_2015_0J['Site ID'].value_counts()

OUTCY203    128
OUTCY298    128
OUTCY174    128
OUTCY004    128
OUTCY205    128
           ... 
OUTCY311     32
OUTCY128     32
OUTCY001     32
OUTCY390     24
OUTCY302     18
Name: Site ID, Length: 67, dtype: int64

In [111]:
# Missing dates by Site ID.
london_outer_2015_0J[london_outer_2015['Month'].isnull()]['Site ID'].value_counts()

OUTCY027    128
OUTCY400    128
OUTCY402    128
Name: Site ID, dtype: int64

In [112]:
# Missing values related to OUTCY027 Site ID.
london_outer_2015_0J[london_outer_2015_0J['Site ID'] == 'OUTCY027']

Survey wave (year)   Site ID     Location Survey date Weather  \
3328                2015  OUTCY027  Morden Road         NaN     NaN   
3329                2015  OUTCY027  Morden Road         NaN     NaN   
3330                2015  OUTCY027  Morden Road         NaN     NaN   
3331                2015  OUTCY027  Morden Road         NaN     NaN   
3332                2015  OUTCY027  Morden Road         NaN     NaN   
...                  ...       ...          ...         ...     ...   
3451                2015  OUTCY027  Morden Road         NaN     NaN   
3452                2015  OUTCY027  Morden Road         NaN     NaN   
3453                2015  OUTCY027  Morden Road         NaN     NaN   
3454                2015  OUTCY027  Morden Road         NaN     NaN   
3455                2015  OUTCY027  Morden Road         NaN     NaN   

             Time                       Period   Direction  Start hour  \
3328  0600 - 0615  Early Morning (06:00-07:00)  Northbound           6   
3329  0615 - 0630  Early Morning (06:00-07:00)  Northbound           6   
3330  0630 - 0645  Early Morning (06:00-07:00)  Northbound           6   
3331  0645 - 0700  Early Morning (06:00-07:00)  Northbound           6   
3332  0700 - 0715        AM peak (07:00-10:00)  Northbound           7   
...           ...                          ...         ...         ...   
3451  2045 - 2100        Evening (19:00-22:00)  Southbound          20   
3452  2100 - 2115        Evening (19:00-22:00)  Southbound          21   
3453  2115 - 2130        Evening (19:00-22:00)  Southbound          21   
3454  2130 - 2145        Evening (19:00-22:00)  Southbound          21   
3455  2145 - 2200        Evening (19:00-22:00)  Southbound          21   

      Start minute  Number of male cycles  Number of female cycles  \
3328             0                     10                        0   
3329            15                      9                        0   
3330            30                     21                        3   
3331            45                     29                        3   
3332             0                     21                        4   
...            ...                    ...                      ...   
3451            45                      3                        0   
3452             0                      5                        0   
3453            15                      5                        0   
3454            30                     10                        0   
3455            45                      2                        1   

      Number of unknown cycles  Total cycles Date  Day Month  Quarter  
3328                         0            10  NaT  NaN   NaN  Unknown  
3329                         0             9  NaT  NaN   NaN  Unknown  
3330                         0            24  NaT  NaN   NaN  Unknown  
3331                         0            32  NaT  NaN   NaN  Unknown  
3332                         0            25  NaT  NaN   NaN  Unknown  
...                        ...           ...  ...  ...   ...      ...  
3451                         0             3  NaT  NaN   NaN  Unknown  
3452                         0             5  NaT  NaN   NaN  Unknown  
3453                         0             5  NaT  NaN   NaN  Unknown  
3454                         0            10  NaT  NaN   NaN  Unknown  
3455                         0             3  NaT  NaN   NaN  Unknown  

[128 rows x 18 columns]

In [113]:
# Row before.
london_outer_2015_0J[3327:3328]

Survey wave (year)   Site ID             Location    Survey date  \
22185                2015  OUTCY174  The Bishop's Avenue  jeu, 02/07/15   

      Weather         Time                 Period   Direction  Start hour  \
22185     Dry  1615 - 1630  PM peak (16:00-19:00)  Northbound          16   

       Start minute  Number of male cycles  Number of female cycles  \
22185            15                      1                        0   

       Number of unknown cycles  Total cycles       Date       Day Month  \
22185                         0             1 2015-07-02  Thursday  July   

      Quarter  
22185      Q3

In [114]:
# Check dates pattern for rows above (related to OUTCY174 Site ID).
london_outer_2015_0J[london_outer_2015_0J['Site ID'] == 'OUTCY174']

# 03/07/2015 followed by 02/07/2015.

Survey wave (year)   Site ID             Location    Survey date  \
22144                2015  OUTCY174  The Bishop's Avenue  ven, 03/07/15   
22145                2015  OUTCY174  The Bishop's Avenue  ven, 03/07/15   
22146                2015  OUTCY174  The Bishop's Avenue  ven, 03/07/15   
22147                2015  OUTCY174  The Bishop's Avenue  ven, 03/07/15   
22148                2015  OUTCY174  The Bishop's Avenue  ven, 03/07/15   
...                   ...       ...                  ...            ...   
22267                2015  OUTCY174  The Bishop's Avenue  jeu, 02/07/15   
22268                2015  OUTCY174  The Bishop's Avenue  jeu, 02/07/15   
22269                2015  OUTCY174  The Bishop's Avenue  jeu, 02/07/15   
22270                2015  OUTCY174  The Bishop's Avenue  jeu, 02/07/15   
22271                2015  OUTCY174  The Bishop's Avenue  jeu, 02/07/15   

      Weather         Time                       Period   Direction  \
22144     Dry  0600 - 0615  Early Morning (06:00-07:00)  Northbound   
22145     Dry  0615 - 0630  Early Morning (06:00-07:00)  Northbound   
22146     Dry  0630 - 0645  Early Morning (06:00-07:00)  Northbound   
22147     Dry  0645 - 0700  Early Morning (06:00-07:00)  Northbound   
22148     Dry  0700 - 0715        AM peak (07:00-10:00)  Northbound   
...       ...          ...                          ...         ...   
22267     Dry  2045 - 2100        Evening (19:00-22:00)  Southbound   
22268     Dry  2100 - 2115        Evening (19:00-22:00)  Southbound   
22269     Dry  2115 - 2130        Evening (19:00-22:00)  Southbound   
22270     Dry  2130 - 2145        Evening (19:00-22:00)  Southbound   
22271     Dry  2145 - 2200        Evening (19:00-22:00)  Southbound   

       Start hour  Start minute  Number of male cycles  \
22144           6             0                      0   
22145           6            15                      0   
22146           6            30                      0   
22147           6            45                      0   
22148           7             0                      2   
...           ...           ...                    ...   
22267          20            45                      2   
22268          21             0                      0   
22269          21            15                      1   
22270          21            30                      0   
22271          21            45                      0   

       Number of female cycles  Number of unknown cycles  Total cycles  \
22144                        0                         0             0   
22145                        0                         0             0   
22146                        0                         0             0   
22147                        0                         0             0   
22148                        0                         0             2   
...                        ...                       ...           ...   
22267                        0                         0             2   
22268                        0                         0             0   
22269                        0                         0             1   
22270                        0                         0             0   
22271                        0                         0             0   

            Date       Day Month Quarter  
22144 2015-07-03    Friday  July      Q3  
22145 2015-07-03    Friday  July      Q3  
22146 2015-07-03    Friday  July      Q3  
22147 2015-07-03    Friday  July      Q3  
22148 2015-07-03    Friday  July      Q3  
...          ...       ...   ...     ...  
22267 2015-07-02  Thursday  July      Q3  
22268 2015-07-02  Thursday  July      Q3  
22269 2015-07-02  Thursday  July      Q3  
22270 2015-07-02  Thursday  July      Q3  
22271 2015-07-02  Thursday  July      Q3  

[128 rows x 18 columns]

In [115]:
# Row after.
london_outer_2015_0J[3456:3457]

Survey wave (year)   Site ID          Location    Survey date Weather  \
23372                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   

              Time                 Period   Direction  Start hour  \
23372  0900 - 0915  AM peak (07:00-10:00)  Southbound           9   

       Start minute  Number of male cycles  Number of female cycles  \
23372             0                      2                        0   

       Number of unknown cycles  Total cycles       Date     Day Month Quarter  
23372                         0             2 2015-07-03  Friday  July      Q3

In [116]:
# Check dates pattern for rows above (related to OUTCY174 Site ID).
london_outer_2015_0J[london_outer_2015_0J['Site ID'] == 'OUTCY183']

# Mixed entries for 03/07/2015 and 02/07/2015.
# Two entries related to 06:00-06:15 (both for 03/07/2015 (with different outputs: 0 and 1) and none for 02/07/2015). 

Survey wave (year)   Site ID          Location    Survey date Weather  \
23296                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23297                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23298                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23299                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23300                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23301                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23302                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23303                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23304                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23305                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23306                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23307                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23308                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23309                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23310                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23311                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23346                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23347                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23348                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23349                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23350                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23351                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23352                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23353                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23354                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23355                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23356                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23357                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23358                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23359                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23360                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23361                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23362                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23363                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23364                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23365                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23366                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23367                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23368                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23369                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23370                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23371                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23372                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23373                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23374                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23375                2015  OUTCY183  Shernhall Street  ven, 03/07/15     Dry   
23410                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23411                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23412                2015  OUTCY183  Shernhall Street  jeu, 02/07/15     Dry   
23413  

In [117]:
# Check dates frequency for OUTCY027 Site ID in the data set.
london_outer[london_outer['Site ID'] == 'OUTCY027']['Date'].value_counts().sort_index()

# Two dates per year (mostly two dates in a row).

2016-06-07    42
2016-07-20    86
2017-05-17    58
2017-05-22    70
2018-06-04    64
2018-06-05    64
2019-06-17    64
2019-06-18    64
2020-10-19    64
2020-10-20    64
2021-04-20    64
2021-04-21    64
Name: Date, dtype: int64

In [118]:
# Missing values related to OUTCY027 Site ID in June 2015.
london_outer_2015_0J[london_outer_2015_0J['Site ID'] == 'OUTCY027']['Time'].value_counts()

# Two entries per time slot => relevant to two dates.

0600 - 0615    2
0615 - 0630    2
1430 - 1445    2
1445 - 1500    2
1500 - 1515    2
              ..
1230 - 1245    2
1245 - 1300    2
1300 - 1315    2
1315 - 1330    2
2145 - 2200    2
Name: Time, Length: 64, dtype: int64

**OBSERVATIONS:**
Missing dates represent 0.3% of all entries. Due to identified inconsistency in date entries (instancies when data for one date is between data for another date; two rows with different cycles counts for the same date, time and site ID) the decision was made to **leave unknown dates as NaT.**

In [119]:
london_outer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375660 entries, 0 to 375659
Data columns (total 18 columns):
 #   Column                    Non-Null Count   Dtype         
---  ------                    --------------   -----         
 0   Survey wave (year)        375660 non-null  int64         
 1   Site ID                   375660 non-null  object        
 2   Location                  375660 non-null  object        
 3   Survey date               374492 non-null  object        
 4   Weather                   374692 non-null  object        
 5   Time                      375660 non-null  object        
 6   Period                    375660 non-null  object        
 7   Direction                 375660 non-null  object        
 8   Start hour                375660 non-null  int64         
 9   Start minute              375660 non-null  int64         
 10  Number of male cycles     375660 non-null  int64         
 11  Number of female cycles   375660 non-null  int64         
 12  Nu

# INNER LONDON DATA SET

In [120]:
# Read the provided CSV file/data set.
london_inner = pd.read_csv('Inner London.csv') 

# Print the output.
print(london_inner.info())
london_inner.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615168 entries, 0 to 615167
Data columns (total 13 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   Survey wave (year)          523776 non-null  float64
 1   Site ID                     523776 non-null  object 
 2   Location                    523776 non-null  object 
 3   Survey date                 521024 non-null  object 
 4   Weather                     519102 non-null  object 
 5   Time                        523770 non-null  object 
 6   Period                      523770 non-null  object 
 7   Direction                   523776 non-null  object 
 8   Start hour                  523770 non-null  float64
 9   Start minute                523770 non-null  float64
 10  Number of private cycles    523776 non-null  float64
 11  Number of cycle hire bikes  523776 non-null  float64
 12  Total cycles                523776 non-null  float64
dtypes: float64(6),

Survey wave (year) Site ID Location Survey date Weather Time Period  \
615163                 NaN     NaN      NaN         NaN     NaN  NaN    NaN   
615164                 NaN     NaN      NaN         NaN     NaN  NaN    NaN   
615165                 NaN     NaN      NaN         NaN     NaN  NaN    NaN   
615166                 NaN     NaN      NaN         NaN     NaN  NaN    NaN   
615167                 NaN     NaN      NaN         NaN     NaN  NaN    NaN   

       Direction  Start hour  Start minute  Number of private cycles  \
615163       NaN         NaN           NaN                       NaN   
615164       NaN         NaN           NaN                       NaN   
615165       NaN         NaN           NaN                       NaN   
615166       NaN         NaN           NaN                       NaN   
615167       NaN         NaN           NaN                       NaN   

        Number of cycle hire bikes  Total cycles  
615163                         NaN           NaN  
615164                         NaN           NaN  
615165                         NaN           NaN  
615166                         NaN           NaN  
615167                         NaN           NaN

In [121]:
# Drop the rows where all elements are missing.
london_inner = london_inner.dropna(how='all')

In [122]:
# Convert 'Survey wave (year)', 'Number of private cycles', 'Number of cycle hire bikes',
# and 'Total_cycles' Dtypes to integer.
london_inner['Survey wave (year)'] = london_inner['Survey wave (year)'].astype(int)
london_inner['Number of private cycles'] = london_inner['Number of private cycles'].astype(int)
london_inner['Number of cycle hire bikes'] = london_inner['Number of cycle hire bikes'].astype(int)
london_inner['Total cycles'] = london_inner['Total cycles'].astype(int)
london_inner.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 523776 entries, 0 to 523775
Data columns (total 13 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   Survey wave (year)          523776 non-null  int64  
 1   Site ID                     523776 non-null  object 
 2   Location                    523776 non-null  object 
 3   Survey date                 521024 non-null  object 
 4   Weather                     519102 non-null  object 
 5   Time                        523770 non-null  object 
 6   Period                      523770 non-null  object 
 7   Direction                   523776 non-null  object 
 8   Start hour                  523770 non-null  float64
 9   Start minute                523770 non-null  float64
 10  Number of private cycles    523776 non-null  int64  
 11  Number of cycle hire bikes  523776 non-null  int64  
 12  Total cycles                523776 non-null  int64  
dtypes: float64(2),

In [123]:
# Any missing values?
london_inner.isnull().sum() 

Survey wave (year)               0
Site ID                          0
Location                         0
Survey date                   2752
Weather                       4674
Time                             6
Period                           6
Direction                        0
Start hour                       6
Start minute                     6
Number of private cycles         0
Number of cycle hire bikes       0
Total cycles                     0
dtype: int64

In [124]:
# Check for duplicates 
london_inner[london_inner.duplicated()].count()

Survey wave (year)            15069
Site ID                       15069
Location                      15069
Survey date                   15069
Weather                       15069
Time                          15069
Period                        15069
Direction                     15069
Start hour                    15069
Start minute                  15069
Number of private cycles      15069
Number of cycle hire bikes    15069
Total cycles                  15069
dtype: int64

In [125]:
# Drop duplicates.
london_inner = london_inner.drop_duplicates()

# View DataFrame.
london_inner.shape

(508707, 13)

In [126]:
# Check for duplicates 
london_inner[london_inner.duplicated()].count()

Survey wave (year)            0
Site ID                       0
Location                      0
Survey date                   0
Weather                       0
Time                          0
Period                        0
Direction                     0
Start hour                    0
Start minute                  0
Number of private cycles      0
Number of cycle hire bikes    0
Total cycles                  0
dtype: int64

Can see that all the duplicates have been removed 

In [127]:
# Check missing values.
london_inner.isnull().sum()

Survey wave (year)               0
Site ID                          0
Location                         0
Survey date                   2752
Weather                       4674
Time                             6
Period                           6
Direction                        0
Start hour                       6
Start minute                     6
Number of private cycles         0
Number of cycle hire bikes       0
Total cycles                     0
dtype: int64

## Cleaning Date and Time related Columns

In [128]:
# Replace blank values with NaN in 'Survey date' column.
london_inner['Survey date'] = london_inner['Survey date'].replace(r'^\s*$', np.nan, regex=True)

In [129]:
# Split 'Survey date' column into two new columns.
london_inner[['Survey_week_day', 'Survey_date']] = london_inner['Survey date'].\
apply(lambda x: pd.Series(str(x).split(',')))

# View DataFrame.
london_inner.head()

Survey wave (year)   Site ID    Location    Survey date Weather  \
0                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
1                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
2                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
3                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
4                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   

          Time                       Period   Direction  Start hour  \
0  0600 - 0615  Early Morning (06:00-07:00)  Northbound         6.0   
1  0615 - 0630  Early Morning (06:00-07:00)  Northbound         6.0   
2  0630 - 0645  Early Morning (06:00-07:00)  Northbound         6.0   
3  0645 - 0700  Early Morning (06:00-07:00)  Northbound         6.0   
4  0700 - 0715        AM peak (07:00-10:00)  Northbound         7.0   

   Start minute  Number of private cycles  Number of cycle hire bikes  \
0           0.0                         1                           0   
1          15.0                         2                           0   
2          30.0                         2                           0   
3          45.0                         4                           0   
4           0.0                         4                           0   

   Total cycles Survey_week_day Survey_date  
0             1             mer    20/05/15  
1             2             mer    20/05/15  
2             2             mer    20/05/15  
3             4             mer    20/05/15  
4             4             mer    20/05/15

In [130]:
# Drop 'Survey_week_day' column.
london_inner = london_inner.drop(columns='Survey_week_day').reset_index(drop=True)

In [131]:
# Remove whitespaces in 'Survey_date' column.
london_inner['Survey_date'] = london_inner['Survey_date'].str.replace(' ', '')

In [132]:
# Convert 'Survey_date' column to datetime dtype.
london_inner['Survey_date_dt'] = pd.to_datetime(london_inner['Survey_date'], format = '%d/%m/%y')

# View DataFrame.
london_inner.head()

Survey wave (year)   Site ID    Location    Survey date Weather  \
0                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
1                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
2                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
3                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
4                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   

          Time                       Period   Direction  Start hour  \
0  0600 - 0615  Early Morning (06:00-07:00)  Northbound         6.0   
1  0615 - 0630  Early Morning (06:00-07:00)  Northbound         6.0   
2  0630 - 0645  Early Morning (06:00-07:00)  Northbound         6.0   
3  0645 - 0700  Early Morning (06:00-07:00)  Northbound         6.0   
4  0700 - 0715        AM peak (07:00-10:00)  Northbound         7.0   

   Start minute  Number of private cycles  Number of cycle hire bikes  \
0           0.0                         1                           0   
1          15.0                         2                           0   
2          30.0                         2                           0   
3          45.0                         4                           0   
4           0.0                         4                           0   

   Total cycles Survey_date Survey_date_dt  
0             1    20/05/15     2015-05-20  
1             2    20/05/15     2015-05-20  
2             2    20/05/15     2015-05-20  
3             4    20/05/15     2015-05-20  
4             4    20/05/15     2015-05-20

In [133]:
# Check missing values.
london_inner.isnull().sum()

Survey wave (year)               0
Site ID                          0
Location                         0
Survey date                   2752
Weather                       4674
Time                             6
Period                           6
Direction                        0
Start hour                       6
Start minute                     6
Number of private cycles         0
Number of cycle hire bikes       0
Total cycles                     0
Survey_date                   2752
Survey_date_dt                2752
dtype: int64

### Missing values in Date and Time related columns

In [134]:
# Select rows containing missing values in 'Survey_date_dt' column.
L_inner_fnl_1 = london_inner[london_inner['Survey_date_dt'].isnull()]

# View DataFrame.
L_inner_fnl_1.head()

Survey wave (year)   Site ID     Location Survey date Weather  \
44672                2015  INNCY350  Spring Hill         NaN     N/a   
44673                2015  INNCY350  Spring Hill         NaN     N/a   
44674                2015  INNCY350  Spring Hill         NaN     N/a   
44675                2015  INNCY350  Spring Hill         NaN     N/a   
44676                2015  INNCY350  Spring Hill         NaN     N/a   

              Time                       Period   Direction  Start hour  \
44672  0600 - 0615  Early Morning (06:00-07:00)  Northbound         6.0   
44673  0615 - 0630  Early Morning (06:00-07:00)  Northbound         6.0   
44674  0630 - 0645  Early Morning (06:00-07:00)  Northbound         6.0   
44675  0645 - 0700  Early Morning (06:00-07:00)  Northbound         6.0   
44676  0700 - 0715        AM peak (07:00-10:00)  Northbound         7.0   

       Start minute  Number of private cycles  Number of cycle hire bikes  \
44672           0.0                         0                           0   
44673          15.0                         0                           0   
44674          30.0                         0                           0   
44675          45.0                         0                           0   
44676           0.0                         0                           0   

       Total cycles Survey_date Survey_date_dt  
44672             0         NaN            NaT  
44673             0         NaN            NaT  
44674             0         NaN            NaT  
44675             0         NaN            NaT  
44676             0         NaN            NaT

In [135]:
# View number of missing values in 'Survey_date_dt' column by year.
L_inner_fnl_1['Survey wave (year)'].value_counts().sort_index()

2015     384
2016     256
2017    1280
2018     640
2019     192
Name: Survey wave (year), dtype: int64

In [136]:
# Select rows without missing values in 'Survey_date_dt' column.
L_inner_fnl_2 = london_inner[~london_inner['Survey_date_dt'].isnull()]

# View DataFrame.
L_inner_fnl_2.head()

Survey wave (year)   Site ID    Location    Survey date Weather  \
0                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
1                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
2                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
3                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
4                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   

          Time                       Period   Direction  Start hour  \
0  0600 - 0615  Early Morning (06:00-07:00)  Northbound         6.0   
1  0615 - 0630  Early Morning (06:00-07:00)  Northbound         6.0   
2  0630 - 0645  Early Morning (06:00-07:00)  Northbound         6.0   
3  0645 - 0700  Early Morning (06:00-07:00)  Northbound         6.0   
4  0700 - 0715        AM peak (07:00-10:00)  Northbound         7.0   

   Start minute  Number of private cycles  Number of cycle hire bikes  \
0           0.0                         1                           0   
1          15.0                         2                           0   
2          30.0                         2                           0   
3          45.0                         4                           0   
4           0.0                         4                           0   

   Total cycles Survey_date Survey_date_dt  
0             1    20/05/15     2015-05-20  
1             2    20/05/15     2015-05-20  
2             2    20/05/15     2015-05-20  
3             4    20/05/15     2015-05-20  
4             4    20/05/15     2015-05-20

In [137]:
# View number of values in 'Survey_date_dt' column by year (excluding missing values).
L_inner_fnl_2['Survey wave (year)'].value_counts().sort_index()

2015    76032
2016    76160
2017    75136
2018    75776
2019    76224
2020    50304
2021    76323
Name: Survey wave (year), dtype: int64

In [138]:
# Find first and last date in 'Survey_date_dt' column.
print(london_inner['Survey_date_dt'].min())
print(london_inner['Survey_date_dt'].max())

# View frequency of dates.
london_inner['Survey_date_dt'].value_counts()

2015-04-13 00:00:00
2021-09-16 00:00:00


2021-05-05    3082
2021-04-22    2888
2017-05-08    2764
2020-09-24    2688
2015-05-06    2612
              ... 
2019-05-18      14
2018-08-02      12
2017-04-10       8
2019-04-28       8
2019-03-12       2
Name: Survey_date_dt, Length: 463, dtype: int64

In [139]:
# Drop 'Survey_date' column.
london_inner = london_inner.drop(columns=['Survey_date']).reset_index(drop=True)

In [140]:
# Rename 'Survey_date_dt' column into 'Date'.
london_inner = london_inner.rename(columns={'Survey_date_dt':'Date'})

# View DataFrame.
london_inner.head()

Survey wave (year)   Site ID    Location    Survey date Weather  \
0                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
1                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
2                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
3                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
4                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   

          Time                       Period   Direction  Start hour  \
0  0600 - 0615  Early Morning (06:00-07:00)  Northbound         6.0   
1  0615 - 0630  Early Morning (06:00-07:00)  Northbound         6.0   
2  0630 - 0645  Early Morning (06:00-07:00)  Northbound         6.0   
3  0645 - 0700  Early Morning (06:00-07:00)  Northbound         6.0   
4  0700 - 0715        AM peak (07:00-10:00)  Northbound         7.0   

   Start minute  Number of private cycles  Number of cycle hire bikes  \
0           0.0                         1                           0   
1          15.0                         2                           0   
2          30.0                         2                           0   
3          45.0                         4                           0   
4           0.0                         4                           0   

   Total cycles       Date  
0             1 2015-05-20  
1             2 2015-05-20  
2             2 2015-05-20  
3             4 2015-05-20  
4             4 2015-05-20

In [141]:
# Add a column with days of the week.
london_inner['Day'] = london_inner['Date'].dt.day_name()

# View DataFrame.
london_inner.head()

Survey wave (year)   Site ID    Location    Survey date Weather  \
0                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
1                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
2                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
3                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   
4                2015  INNCY001  Grove Road  mer, 20/05/15     Dry   

          Time                       Period   Direction  Start hour  \
0  0600 - 0615  Early Morning (06:00-07:00)  Northbound         6.0   
1  0615 - 0630  Early Morning (06:00-07:00)  Northbound         6.0   
2  0630 - 0645  Early Morning (06:00-07:00)  Northbound         6.0   
3  0645 - 0700  Early Morning (06:00-07:00)  Northbound         6.0   
4  0700 - 0715        AM peak (07:00-10:00)  Northbound         7.0   

   Start minute  Number of private cycles  Number of cycle hire bikes  \
0           0.0                         1                           0   
1          15.0                         2                           0   
2          30.0                         2                           0   
3          45.0                         4                           0   
4           0.0                         4                           0   

   Total cycles       Date        Day  
0             1 2015-05-20  Wednesday  
1             2 2015-05-20  Wednesday  
2             2 2015-05-20  Wednesday  
3             4 2015-05-20  Wednesday  
4             4 2015-05-20  Wednesday

In [142]:
# Extract year from Date column.
london_inner['Year'] = london_inner['Date'].dt.strftime('%Y')

# Replace NaN values to 0 and convert values in the column to integer.
london_inner['Year'] = london_inner['Year'].fillna(0)
london_inner['Year'] = london_inner['Year'].astype(int)

# Compare extracted year to Survey_wave_year column.
london_inner[(london_inner['Survey wave (year)'] != london_inner['Year']) & (london_inner['Year'] > 0)]

# Values in Year and Survey wave (year) columns do not match in 384 rows (wrong year in Survey wave (year) column).
# Use Year column in calculations.

Survey wave (year)   Site ID        Location    Survey date Weather  \
123008                2016  INNCY365  Wildcroft Road  lun, 15/05/17     N/a   
123009                2016  INNCY365  Wildcroft Road  lun, 15/05/17     N/a   
123010                2016  INNCY365  Wildcroft Road  lun, 15/05/17     N/a   
123011                2016  INNCY365  Wildcroft Road  lun, 15/05/17     N/a   
123012                2016  INNCY365  Wildcroft Road  lun, 15/05/17     N/a   
...                    ...       ...             ...            ...     ...   
378619                2019  INNCY570  Myatt's Fields  mer, 18/04/18     Dry   
378620                2019  INNCY570  Myatt's Fields  mer, 18/04/18     Dry   
378621                2019  INNCY570  Myatt's Fields  mer, 18/04/18     Dry   
378622                2019  INNCY570  Myatt's Fields  mer, 18/04/18     Dry   
378623                2019  INNCY570  Myatt's Fields  mer, 18/04/18     Dry   

               Time                       Period   Direction  Start hour  \
123008  0600 - 0615  Early Morning (06:00-07:00)  Northbound         6.0   
123009  0615 - 0630  Early Morning (06:00-07:00)  Northbound         6.0   
123010  0630 - 0645  Early Morning (06:00-07:00)  Northbound         6.0   
123011  0645 - 0700  Early Morning (06:00-07:00)  Northbound         6.0   
123012  0700 - 0715        AM peak (07:00-10:00)  Northbound         7.0   
...             ...                          ...         ...         ...   
378619  2045 - 2100        Evening (19:00-22:00)   Westbound        20.0   
378620  2100 - 2115        Evening (19:00-22:00)   Westbound        21.0   
378621  2115 - 2130        Evening (19:00-22:00)   Westbound        21.0   
378622  2130 - 2145        Evening (19:00-22:00)   Westbound        21.0   
378623  2145 - 2200        Evening (19:00-22:00)   Westbound        21.0   

        Start minute  Number of private cycles  Number of cycle hire bikes  \
123008           0.0                         1                           0   
123009          15.0                         1                           0   
123010          30.0                         0                           0   
123011          45.0                         0                           0   
123012           0.0                         0                           0   
...              ...                       ...                         ...   
378619          45.0                         0                           0   
378620           0.0                         0                           0   
378621          15.0                         0                           0   
378622          30.0                         0                           0   
378623          45.0                         0                           0   

        Total cycles       Date        Day  Year  
123008             1 2017-05-15     Monday  2017  
123009             1 2017-05-15     Monday  2017  
123010             0 2017-05-15     Monday  2017  
123011             0 2017-05-15     Monday  2017  
123012             0 2017-05-15     Monday  2017  
...              ...        ...        ...   ...  
378619             0 2018-04-18  Wednesday  2018  
378620             0 2018-04-18  Wednesday  2018  
378621             0 2018-04-18  Wednesday  2018  
378622             0 2018-04-18  Wednesday  2018  
378623             0 2018-04-18  Wednesday  2018  

[384 rows x 16 columns]

In [143]:
# Replace missing years in the Year column with years from Survey_wave_year column.
london_inner['Year'] = np.where((london_inner['Survey wave (year)'] != london_inner['Year']) & 
                                 (london_inner['Year'] == 0), 
                                 london_inner['Survey wave (year)'],
                                 london_inner['Year'])

# Check the output.
london_inner[london_inner['Year'] == 0]

Empty DataFrame
Columns: [Survey wave (year), Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of private cycles, Number of cycle hire bikes, Total cycles, Date, Day, Year]
Index: []

In [144]:
# Extract year from Date column.
london_inner['Month'] = london_inner['Date'].dt.strftime('%B')

In [145]:
# Create a new column 'Quarter' and assign months from Month columns to the relevant calendar quarters.
london_inner['Quarter'] = ''

london_inner.loc[(london_inner['Month'] ==  'January') | 
                  (london_inner['Month'] ==  'February') |
                  (london_inner['Month'] ==  'March'), 
                  'Quarter'] = 'Q1'

london_inner.loc[(london_inner['Month'] ==  'April') | 
                  (london_inner['Month'] ==  'May') |
                  (london_inner['Month'] ==  'June'), 
                  'Quarter'] = 'Q2'

london_inner.loc[(london_inner['Month'] ==  'July') | 
                  (london_inner['Month'] ==  'August') |
                  (london_inner['Month'] ==  'September'), 
                  'Quarter'] = 'Q3'

london_inner.loc[(london_inner['Month'] ==  'October') | 
                  (london_inner['Month'] ==  'November') |
                  (london_inner['Month'] ==  'December'), 
                  'Quarter'] = 'Q4'

# Convert empty cells into NaN values and replace with 'Unknown'.
london_inner['Quarter'] = london_inner['Quarter'].replace('', np.nan, regex = True)
london_inner['Quarter'] = london_inner['Quarter'].fillna('Unknown')

In [146]:
london_inner['Period'].value_counts()

Inter-peak (10:00-16:00)       190828
AM peak (07:00-10:00)           95418
PM peak (16:00-19:00)           95390
Evening (19:00-22:00)           95293
Early Morning (06:00-07:00)     31772
Name: Period, dtype: int64

In [147]:
# Check if Time periods are in line with Period column for Early Morning (06:00-07:00).
EM = london_inner[london_inner['Period'] == 'Early Morning (06:00-07:00)']

EM[(EM['Time'] != '0600 - 0615') & (EM['Time'] != '0615 - 0630') & (EM['Time'] != '0630 - 0645') &
  (EM['Time'] != '0645 - 0700')]

Empty DataFrame
Columns: [Survey wave (year), Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of private cycles, Number of cycle hire bikes, Total cycles, Date, Day, Year, Month, Quarter]
Index: []

In [148]:
# Check if Time periods are in line with Period column for AM peak (07:00-10:00).
AP = london_inner[london_inner['Period'] == 'AM peak (07:00-10:00)']

AP[(AP['Time'] != '0700 - 0715') & (AP['Time'] != '0715 - 0730') & (AP['Time'] != '0730 - 0745') &
  (AP['Time'] != '0745 - 0800') & (AP['Time'] != '0800 - 0815') & (AP['Time'] != '0815 - 0830') & 
   (AP['Time'] != '0830 - 0845') & (AP['Time'] != '0845 - 0900') & (AP['Time'] != '0900 - 0915') & 
   (AP['Time'] != '0915 - 0930') & (AP['Time'] != '0930 - 0945') & (AP['Time'] != '0945 - 1000')]

Empty DataFrame
Columns: [Survey wave (year), Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of private cycles, Number of cycle hire bikes, Total cycles, Date, Day, Year, Month, Quarter]
Index: []

In [149]:
# Check if Time periods are in line with Period column for Inter-peak (10:00-16:00).
IP = london_inner[london_inner['Period'] == 'Inter-peak (10:00-16:00)']

IP[(IP['Time'] != '1000 - 1015') & (IP['Time'] != '1015 - 1030') & (IP['Time'] != '1030 - 1045') &
  (IP['Time'] != '1045 - 1100') & (IP['Time'] != '1100 - 1115') & (IP['Time'] != '1115 - 1130') & 
   (IP['Time'] != '1130 - 1145') & (IP['Time'] != '1145 - 1200') & (IP['Time'] != '1200 - 1215') & 
   (IP['Time'] != '1215 - 1230') & (IP['Time'] != '1230 - 1245') & (IP['Time'] != '1245 - 1300') &
  (IP['Time'] != '1300 - 1315') & (IP['Time'] != '1315 - 1330') & (IP['Time'] != '1330 - 1345') &
  (IP['Time'] != '1345 - 1400') & (IP['Time'] != '1400 - 1415') & (IP['Time'] != '1415 - 1430') & 
   (IP['Time'] != '1430 - 1445') & (IP['Time'] != '1445 - 1500') & (IP['Time'] != '1500 - 1515') & 
   (IP['Time'] != '1515 - 1530') & (IP['Time'] != '1530 - 1545') & (IP['Time'] != '1545 - 1600')]

Empty DataFrame
Columns: [Survey wave (year), Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of private cycles, Number of cycle hire bikes, Total cycles, Date, Day, Year, Month, Quarter]
Index: []

In [150]:
# Check if Time periods are in line with Period column for PM peak (16:00-19:00).
PP = london_inner[london_inner['Period'] == 'PM peak (16:00-19:00)']

PP[(PP['Time'] != '1600 - 1615') & (PP['Time'] != '1615 - 1630') & (PP['Time'] != '1630 - 1645') &
  (PP['Time'] != '1645 - 1700') & (PP['Time'] != '1700 - 1715') & (PP['Time'] != '1715 - 1730') & 
   (PP['Time'] != '1730 - 1745') & (PP['Time'] != '1745 - 1800') & (PP['Time'] != '1800 - 1815') & 
   (PP['Time'] != '1815 - 1830') & (PP['Time'] != '1830 - 1845') & (PP['Time'] != '1845 - 1900')]

Empty DataFrame
Columns: [Survey wave (year), Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of private cycles, Number of cycle hire bikes, Total cycles, Date, Day, Year, Month, Quarter]
Index: []

In [151]:
# Check if Time periods are in line with Period column for Evening (19:00-22:00).
E = london_inner[london_inner['Period'] == 'Evening (19:00-22:00)']

E[(E['Time'] != '1900 - 1915') & (E['Time'] != '1915 - 1930') & (E['Time'] != '1930 - 1945') &
  (E['Time'] != '1945 - 2000') & (E['Time'] != '2000 - 2015') & (E['Time'] != '2015 - 2030') & 
   (E['Time'] != '2030 - 2045') & (E['Time'] != '2045 - 2100') & (E['Time'] != '2100 - 2115') & 
   (E['Time'] != '2115 - 2130') & (E['Time'] != '2130 - 2145') & (E['Time'] != '2145 - 2200')]

Empty DataFrame
Columns: [Survey wave (year), Site ID, Location, Survey date, Weather, Time, Period, Direction, Start hour, Start minute, Number of private cycles, Number of cycle hire bikes, Total cycles, Date, Day, Year, Month, Quarter]
Index: []

**OBSERVATIONS:**
2752 entries have no dates (0.5% of all rows); decision was made to leave it as NaT.